### PR TITLE
fix(Panel): rerender Tab on prop changes

### LINKED ISSUE #4021: Linting Tab is not updated
### Describe the bug

image

### Steps to reproduce

1. Create a Diagram with errors
2. Open the Problems panel
3. No errors are shown

### Expected behavior

Problems are shown

## Camunda Modeler system information
 * Version: 5.18.0-rc.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda 8

### Additional context

With https://github.com/camunda/camunda-modeler/pull/3998, we add Tabs in a different way. Unfortunately, they are not updated after initial render

### PR DESCRIPTION
**Pull request by marstamm**
fixes #4021

Recording 2023-12-11 at 16 29 49

We now rerender the Tab entry when the content (children/label/id/...) changes

### CODE REVIEW

File: client/src/app/panel/__tests__/PanelSpec.js [hunk 1]
```diff
@@ -77,6 +77,47 @@ describe('<Panel>', function() {
...
+      expect(wrapper.find('.panel__link').at(0).find('.panel__link-label').text()).to.equal('Foo');
+      expect(wrapper.find('.panel__link').at(0).hasClass('panel__link--active')).to.be.true;
+
+      // when
+      wrapper.find(CustomComponent).setState({ label: 'Bar' });
+
+      // then
+      return expectEventually(() => {
+        expect(wrapper.find('.panel__link').at(0).find('.panel__link-label').text()).to.equal('Bar');
+        expect(wrapper.find('.panel__link').at(0).hasClass('panel__link--active')).to.be.true;
```
Comment (nikku) [inline client/src/app/panel/__tests__/PanelSpec.js:116]: This one is redundant, right?

Comment (marstamm) [reply client/src/app/panel/__tests__/PanelSpec.js:116]: We want to check that the Label has changed but is still selected and active

File: client/src/app/panel/Panel.js [hunk 2]
```diff
@@ -144,40 +144,42 @@ function Tab(props) {
...
-  });
-
-  const TabContent = {
-    id: id || label,
-    priority,
-    link: Link,
-    actions: Actions,
-    body: children
-  };
+  const TabContent = useMemo(() => {
```
Comment (nikku) [inline client/src/app/panel/Panel.js:147]: What happens here, and why?

Comment (marstamm) [reply client/src/app/panel/Panel.js:147]: We recreate the TabContent every time a Prop changes (instead of every rerender). This allows us to react to changed content [here](https://github.com/camunda/camunda-modeler/blob/73623ed3c9d9a16b628af366890ed836b94ed330/client/src/app/panel/Panel.js#L182) and update the tab in the `TabContext`

Comment (marstamm) [reply client/src/app/panel/Panel.js:147]: Using `useMemo` here prevents unnecessary updates of the `TabContext`

Comment (nikku) [reply client/src/app/panel/Panel.js:147]: Makes sense now. So it broke turning it into a functional component.
