### PR TITLE
Fix problems in React Strict Mode & errors in dev mode

### LINKED ISSUE #5872: Settings modal does not open after clicking "Manage connections" in dev mode
### What should we do?

Open settings modal after clicking "Manage connections" when running the development version of the app.

**Note:** this issue is a task (not a bug) because I cannot reproduce this on the `main` branch. I can reproduce this on `develop`, however).

### Why should we do it?

Users will not be able manage their connections in the next release unless this is fixed.

### PR DESCRIPTION
**Pull request by jarekdanielak**
Closes https://github.com/camunda/camunda-modeler/issues/5872

### Proposed Changes

We've recently enabled React Strict Mode for local modeler start (https://github.com/camunda/camunda-modeler/pull/5768). It surfaced a bunch of problems that could _potentially_ cause problems in the actual production build. 

This PR attempts to proactively fix them:

1. Do not throw from `Settings#register` when a setting is already registered. This actually crashes settings plugin on curent `develop`.
2. Return `unsubscribe` callback from `Settings#subscribe` to enable proper clean-up. Use it in TestClient plugin & connection manager.
3. More null-checks for Monaco editor in the RPA tab.
4. Handle App's `client:started` subscription similarly to how other subscriptions are handled.
5. Rewrite TestClient plugin to a functional component - easier to demonstrate how Settings API is supposed to be used.
6. Increase max event listeners for `App#events` to get rid of the "potential memory leak" warning.

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [ ] Pull request __establishes context__
  * [ ] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [ ] __Screenshots or short videos__ showing UI/UX changes
  * [ ] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

File: client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js [hunk 1]
```diff
@@ -218,87 +218,101 @@ describe('<RPAEditor>', function() {
 
     describe('behavior', function() {
 
+      // More time for debounced linting
```
Comment (Buckwich) [inline client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js:221]: are these changes actually related to strict mode? I thought it would not be active during testing

Comment (jarekdanielak) [reply client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js:221]: Nah, just sneaking in a general improvement to tests stability. This one often fails on macOS CI.

**Comment by barmac** [comment]
This seems to fix https://github.com/camunda/camunda-modeler/issues/5872

**Comment by jarekdanielak** [comment]
@barmac yup, added to the top comment.

**Comment by jarekdanielak** [comment]
I'll have a look into the [Form tab error you reported](https://camunda.slack.com/archives/GP70M0J6M/p1776258958217179). It's related to strict mode.

File: client/src/app/AppParent.js [hunk 2]
```diff
@@ -340,9 +340,13 @@ export default class AppParent extends PureComponent {
 
     const backend = this.getBackend();
 
-    backend.once('client:started', this.handleStarted);
+    this.prereadyState = this.prereadyState || {
+      files: [],
+      workspace: {}
+    };
```
Comment (barmac) [inline client/src/app/AppParent.js:346]: Why do we need to reset this?

Comment (jarekdanielak) [reply client/src/app/AppParent.js:346]: It's a guard against a race condition (which we notice only in the strict mode) when `handleStarted` sets `prereadyState` to `null` before the second mount.

**Comment by barmac** [comment]
@jarekdanielak Overall it looks good. There's only [one fragment which I find confusing](https://github.com/camunda/camunda-modeler/pull/5860#discussion_r3129714501). Can you please clarify this? Then I think we can merge the PR.

File: client/src/app/AppParent.js (hunk 2 above)
Comment (barmac) [reply client/src/app/AppParent.js:346]: Got it. We don't expect the AppParent to mount twice, but this is what the strict mode enforces.
