### PR TITLE
fix: errors will now show properly when dragging in the wrong file type with 'disable-platform' on

### LINKED ISSUE #2548: Cryptic error message when DMN is dropped on "Zeebe" Modeler
__Describe the Bug__

Given I set `--disable-platform` flag, when I drop a DMN file on the modeler, it displays:

image

__Steps to Reproduce__

See above.

__Expected Behavior__

It should say "... is not a BPMN or Form file."

__Environment__

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: `develop`
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #2548

### CODE REVIEW

File: client/src/app/__tests__/TabsProviderSpec.js [hunk 1]
```diff
@@ -424,17 +424,69 @@ describe('TabsProvider', function() {
...
+      const providerNames = tabsProvider.getProviderNames();
 
-    // then
-    expect(providerNames).to.eql([ 'BPMN', 'CMMN', 'DMN', 'FORM' ]);
+      // then
+      expect(providerNames).to.eql(['BPMN', 'DMN', 'FORM']);
+
+    });
+
+    it('should return all provider names', function() {
```
Comment (pinussilvestrus) [inline client/src/app/__tests__/TabsProviderSpec.js:443]: Minor thing: We (try) to structure our tests in a way to keep _two_ newlines between each `it` and `describe` block. So

```js
it('getProviders');


describe('#getProviderNames', function()) {
  
  it('should return default provider names');
  
  
  it('should return all provider names');
  
  
  it('should return cloud provider names only');
  
  
  it('should return platform provider names only');
  
});
```

Seems like the newline was even missed in the previous state, so let's get it clean here 🙂

File: client/src/app/__tests__/TabsProviderSpec.js [hunk 2]
```diff
@@ -424,17 +424,69 @@ describe('TabsProvider', function() {
...
 
-    // when
-    const providerNames = tabsProvider.getProviderNames();
+      // when
+      const providerNames = tabsProvider.getProviderNames();
 
-    // then
-    expect(providerNames).to.eql([ 'BPMN', 'CMMN', 'DMN', 'FORM' ]);
+      // then
+      expect(providerNames).to.eql(['BPMN', 'DMN', 'FORM']);
```
Comment (pinussilvestrus) [inline client/src/app/__tests__/TabsProviderSpec.js:439]: Let's try to add spaces inside the array entries. I remember we recently added a [linting rule for that](https://github.com/bpmn-io/eslint-plugin-bpmn-io/commit/8dc9959e658b96b013780a3105713b5f3e5ce76b), but seems like it did not end yet inside the Modeler.

```js
expect(providerNames).to.eql([ 'BPMN', 'DMN', 'FORM' ]);
```

Same goes for the other name arrays below.

**Review by pinussilvestrus — COMMENTED** [review]
Works like a charm for me 🚀  Just some minor code formatting things, but besides, good job 👍 

Bildschirmfoto 2022-01-04 um 13 36 29

Maybe we can update the commit message to be a bit shorter. The commit should also reference the issue it is closing. What do you think about

```text
fix: add missing names for cloud providers

Closes #2548 
```

**Review by pinussilvestrus — APPROVED** [review]
Thanks for following up! As the last minor adjustment I squashed the two commits together into a single one, this keeps our commit history clean, we should avoid more commits on top to just fix simple quirks in a PR 👍 

Good job!
