### PR TITLE
fix: remove non-existing linting module usage in forms

### LINKED ISSUE #3640: Form editor crashes on nightly
### Describe the bug

With https://github.com/camunda/camunda-modeler/pull/3509, we broke the forms editor.

image

### Steps to reproduce

1. do this
2. do that
3. now this happens

### Expected behavior

No crash, editor should be usable.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: nightly
- Execution Platform: [e.g. Camunda Platform, Camunda Cloud]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barmac**
Closes #3640

The issue went under the radar because in tests we mock Forms Editor even to an extent where we mock non-existing module 🤡

### CODE REVIEW

**Comment by barmac** [comment]
> This Pull Request targets `develop` branch, but contains `fix` commits.
> 
> Consider targeting `master` instead.

Ignore this; the bug exists on `develop` only.

File: client/src/app/tabs/form/__tests__/FormEditorSpec.js [hunk 1]
```diff
@@ -815,6 +815,29 @@ describe('<FormEditor>', function() {
...
+        };
+
+        // when
+        try {
+          await renderEditor(schema, props);
+        } catch (error) {
+
+          // then
+          expect(error).not.to.exist;
+        }
```
Comment (marstamm) [inline client/src/app/tabs/form/__tests__/FormEditorSpec.js:838]: This test still succeeds when the function throws, but no error is created (e.g. `throw null;`)
Unfortunately, `expect().not.to.throw` does not work with async functions. We could ensure it fails on all throws like this

```suggestion
        try {
          await renderEditor(schema, props);
        } catch (error) {

          // then
          // should not throw
          expect(true).to.false;
        }
```

Comment (marstamm) [reply client/src/app/tabs/form/__tests__/FormEditorSpec.js:838]: Bit of an edge case, as we would expect an error to be always thrown

Comment (nikku) [reply client/src/app/tabs/form/__tests__/FormEditorSpec.js:838]: What we want to do is this:

```
let err;

try { something } catch (error) { err = error }

// then
expect(err).to.something;
```

Comment (barmac) [reply client/src/app/tabs/form/__tests__/FormEditorSpec.js:838]: I'll rewrite it though I have not encountered `throw null;` yet.

Comment (marstamm) [reply client/src/app/tabs/form/__tests__/FormEditorSpec.js:838]: > I'll rewrite it though I have not encountered throw null; yet.

Throwing `null` or `undefined` would be worst practice 😄

**Review by marstamm — APPROVED** [review]
LGTM
