### PR TITLE
fix: adjusted logging for toast notifications

### LINKED ISSUE #2793: Error doesn't appear in the log
__Describe the Bug__

If start instance failed but the user did not click on the "show error in log" link, the error does not appear on the log at all.

(I assume the same behavior for deployment errors)

__Steps to Reproduce__

1. Create a start instance failure
2. Do not (!) click on the error message link, wait until message is closed or close it via X
3. Open log view from status bar
4. No error is shown

Screen recording:
https://user-images.githubusercontent.com/938244/156136839-0dfcced7-cf27-4635-8939-33adbdeaa017.mov

__Expected Behavior__

Write errors into the log independent from the interaction with the error notification.

__Environment__

 * Version: 5.0.0-nightly.20220217
 * Operating System: Mac OS 12.2.1 
 * Plugins: Cloud Connect
 * Execution Platform: BPMN - Camunda Platform

### PR DESCRIPTION
**Pull request by Skaiir**
Closes #2793

### CODE REVIEW

File: client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js [hunk 1]
```diff
@@ -900,8 +900,8 @@ describe('<StartInstanceTool>', () => {
 
       const actionSpy = sinon.spy(),
             actionTriggered = {
-              emitEvent: 'emit-event',
-              type: 'deployment.done',
+              emitEvent: 'open-log',
+              type: null,
```
Comment (smbea) [inline client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js:904]: Why does the notification type become `null`?

File: client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js [hunk 2]
```diff
@@ -414,19 +414,24 @@ export default class StartInstanceTool extends PureComponent {
...
 
+     log(logMessage);
+
      const content = <button
-       onClick={ ()=> log(logMessage) }>
+       onClick={ () => triggerAction('open-log') }>
        See the log for further details.
      </button>;
 
+
```
Comment (smbea) [inline client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js:434]: Sorry about being picky but let's remove this unnecessary double spacing here

File: client/src/app/App.js [hunk 3]
```diff
@@ -1142,8 +1142,11 @@ export class App extends PureComponent {
    * @param {string} category - Category of message.
    * @param {string} action - Action to be triggered.
```
Comment (pinussilvestrus) [inline client/src/app/App.js:1143]: Make sure to also update the docs 👍

File: client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js (hunk 1 above)
Comment (Skaiir) [reply client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js:904]: Basically the events that are defined at the very root of the application are defined as `event-name` while those which go through our event classes as `emit-event:event.type`. I've defined open-log along with the log event, to be consistent, which follows the legacy pattern (in any case the log is due for a rework some time in the future). 

The actual type we have here is 'undefined' but I've modified the mock constructor to return null to be more explicit (line 1224) I could also return undefined but I felt in this case since we expect no type specifically, null is suited.

File: client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js (hunk 2 above)
Comment (Skaiir) [reply client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js:434]: One day I'll prove my IDE is sentient and doesn't have my interest at heart 😆, will remove.

File: client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js (hunk 1 above)
Comment (smbea) [reply client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js:904]: Then couldn't we omit the `type: null` here?

Comment (Skaiir) [reply client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js:904]: Yeah it should work since we're using `==` in the mock. I'll just change it to return undefined instead though.

Comment (Skaiir) [reply client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js:904]: The mock I mean, I'll implement your suggestion.

**Review by smbea — APPROVED** [review]
Good to go
