### PR TITLE
Track serviceTask metrics

### LINKED ISSUE #2218: Usage of ServiceTasks is tracked via E.T.
> **This is an epic issue which may be broken down into multiple tasks, if needed**

__What should we do?__

We would like to better understand how `bpmn:ServiceTask` elements are used. Hence we would like to track the following metrics via E.T.:

Metric Name | Description | File Type | Sent with Event
-- | -- | -- | --
tasks.serviceTask.count | number of tasks of type serviceTask | BPMN-Camunda, BPMN-Zeebe | diagramOpened, deployment
tasks.serviceTask.implementation.count | number of tasks of type serviceTask which have an implementation | BPMN-Camunda, BPMN-Zeebe | diagramOpened, deployment
tasks.serviceTask.implementation.java | number of tasks of type serviceTask with "Java Class" implementation | BPMN-Camunda | diagramOpened, deployment
tasks.serviceTask.implementation.expression | number of tasks of type serviceTask with "Expression" implementation | BPMN-Camunda | diagramOpened, deployment
tasks.serviceTask.implementation.delegate | number of tasks of type serviceTask with "Delegate Expression" implementation | BPMN-Camunda | diagramOpened, deployment
tasks.serviceTask.implementation.external | number of tasks of type serviceTask with "External" implementation | BPMN-Camunda, BPMN-Zeebe | diagramOpened, deployment
tasks.serviceTask.implementation.connector | number of tasks of type serviceTask with "Connector" implementation | BPMN-Camunda | diagramOpened, deployment

In analogy to `serviceTask`s, this will be embedded as following:
```json
{
  "diagramMetrics": {
    "processVariablesCount": 3,
    "tasks": {
      "userTask": {
        "count": 7,
          "form": {
            "count": 7,
            "embedded": 3,
            "camundaForms": 1,
            "external": 1,
            "generated": 1,
            "other": 1
          },
       "serviceTask": {
        "count": 5,
        "implementation": {
          "count": 5,
          "java": 1,
          "expression": 1,
          "delegate": 2,
          "external": 0,
          "connector": 1
        }
      }
    }
  }
}
```

In particular we need to:

- [x] Track serviceTask counts for zeebe and camunda diagrams
- [ ] Update the [Telemetry documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/telemetry)

__Why should we do it?__
This will help to better design the serviceTask support in the future of the Camunda Modeler

__Context__
[Telemetry documentation](https://github.com/camunda/camunda-modeler/tree/develop/docs/telemetry)

### PR DESCRIPTION
**Pull request by MaxTru**
closes #2218

### CODE REVIEW

File: client/src/util/metrics/serviceTasks.js [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+  const isDelegate = (serviceTask) => 'delegateExpression' in serviceTask;
+  const isExternal = (serviceTask) => 'type' in serviceTask && serviceTask.get('type') === 'external';
+  const isConnector = (serviceTask) => getExtensionElements(serviceTask, 'camunda:Connector').length;
+
+  return {
+    count: serviceTasks.filter((serviceTask) => isJava(serviceTask) ||
+                                                isExpression(serviceTask) ||
+                                                isDelegate(serviceTask) ||
+                                                isExternal(serviceTask) ||
+                                                isConnector(serviceTask)).length,
```
Comment (barmac) [inline client/src/util/metrics/serviceTasks.js:67]: `isConnector` already returns a number via `.length`, so this should fail in tests if I get it correctly

Comment (barmac) [reply client/src/util/metrics/serviceTasks.js:67]: Sorry, I missed closing parenthesis. Nevermind!

**Review by barmac — APPROVED** [review]
Looks good
