### PR TITLE
fix(app): call Dialog#showDialog with correct arguments

### LINKED ISSUE #1301: Opening empty file error dialog is empty
dialog

Hint: [`Dialog#showDialog`](https://github.com/camunda/camunda-modeler/blob/master/app/lib/dialog.js#L52) called with wrong arguments.

### PR DESCRIPTION
**Pull request by philippfromme**
`Dialog#showDialog` was called with wrong arguments.

Closes #1301

### CODE REVIEW

File: app/test/spec/dialog-spec.js [hunk 1]
```diff
@@ -380,6 +376,58 @@ describe('Dialog', function() {
...
+        name: 'foo.txt'
+      };
+
+      electronDialog.setResponse(0);
+
+      // when
+      await dialog.showOpenFileErrorDialog(options);
+
+      // then
+      var dialogArgs = getDialogArgs(electronDialog.showMessageBox);
```
Comment (barmac) [inline app/test/spec/dialog-spec.js]:
```suggestion
      const dialogArgs = getDialogArgs(electronDialog.showMessageBox);
```

File: app/test/spec/dialog-spec.js [hunk 2]
```diff
@@ -380,6 +376,58 @@ describe('Dialog', function() {
...
+        detail: 'bar'
+      };
+
+      electronDialog.setResponse(0);
+
+      // when
+      await dialog.showOpenFileErrorDialog(options);
+
+      // then
+      var dialogArgs = getDialogArgs(electronDialog.showMessageBox);
```
Comment (barmac) [inline app/test/spec/dialog-spec.js]:
```suggestion
      const dialogArgs = getDialogArgs(electronDialog.showMessageBox);
```
