### PR TITLE
2388 add report feedback

### LINKED ISSUE #2388: Copy version info, installed plugins, OS
As a user, it would encourage me to provide feedback more often if I could easily copy the version info, installed plugins, O, etc. out of the tool. Especially the version number of nightly builds and the list of installed plugins takes a lot of time to manually type into a bug report and is likely not as precise as it could be when exported by the tool.

Bonus would be some more direct integration of feedback in the UI like in Cawemo.

### PR DESCRIPTION
**Pull request by MaxTru**
closes #2388

-----

System info looks like this:

```
## Camunda Modeler system information
 * Version: 4.9.0
 * Operating System: Linux x86_64 amd64
 * Plugins: test-client, test-editor-events, test-script-error, test
 * Execution Platform: BPMN - Camunda Platform
```

### CODE REVIEW

**Comment by andreasgeier** [comment]
Please check:

- color of the feedback icon is not aligned with other icons (e.g. deploy, run) –> should be #3B3B3B
- change the color of the icon to white on active state (when bg is blue), see deploy + run for expected behavior
- there is white space below the status bar; editor is scrollable –> please fix

The overlay is already awesome! Let's decide about an email address in the afternoon.

**Comment by MaxTru** [comment]
[This commit](https://github.com/camunda/camunda-modeler/commit/8c344765ee30772e0a81bafbfffe31cf69c46b04) broke fetching of execPlatform... Will adjust

File: client/src/plugins/report-feedback/ClipboardCopySystemInfo.js [hunk 1]
```diff
@@ -0,0 +1,102 @@
...
+
+    this._backend = getGlobal('backend');
+    this._plugins = getGlobal('plugins');
+    this._config = getGlobal('config');
+    this._activeTab = activeTab;
+  }
+
+  async clipboardCopy(config) {
+    const systemInfo = await this._compileSystemInfoString(config);
+    this._backend.send('clipboard:write-text', { text: systemInfo });
```
Comment (pinussilvestrus) [inline client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: We have a copy function in the [Log](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/Log.js#L154) which is using browser API only. Is there any reason why we are using it differently here (via electron API)?

Comment (pinussilvestrus) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: Ok probably because we don't have selections here ...

Comment (MaxTru) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: yep 

> Please check:
> 
> * color of the feedback icon is not aligned with other icons (e.g. deploy, run) –> should be #3B3B3B
> * change the color of the icon to white on active state (when bg is blue), see deploy + run for expected behavior
> * there is white space below the status bar; editor is scrollable –> please fix
> 
> The overlay is already awesome! Let's decide about an email address in the afternoon.

All resolved.

New build:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-win-x64.zip

**Comment by MaxTru** [comment]
> Please check:
> 
> * color of the feedback icon is not aligned with other icons (e.g. deploy, run) –> should be #3B3B3B
> * change the color of the icon to white on active state (when bg is blue), see deploy + run for expected behavior
> * there is white space below the status bar; editor is scrollable –> please fix
> 
> The overlay is already awesome! Let's decide about an email address in the afternoon.

All resolved.

New build:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2388-add-report-feedback/camunda-modeler-2388-add-report-feedback-win-x64.zip

File: client/src/plugins/report-feedback/ClipboardCopySystemInfo.js (hunk 1 above)
Comment (MaxTru) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: Hm, well we could have the text in some transient hidden area and select and copy from there.

But I think going via the designated electron API is not a bad thing is it?

Comment (pinussilvestrus) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: I would even argue using the electron API is the better approach 👍  I would use it instead of the browser API whenever possible. Everything else would look like a hack to me.

Just wanted to make sure we know that we have different ways of copying here 🙂

Comment (nikku) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: Instead of doing `this._backend.send('clipboard:write-text', { text: systemInfo });` the least thing we could do is to move "copying to clipboard" behind an API we own (i.e. `remote`). This way it does not matter for a feature developer which way we do it.

So first important:

* Consolidate `copy` behind an API we own

Next:

* Use copy consistently (we use the API everywhere)

That would be best, if feasible of course.

**Review by andreasgeier — APPROVED** [review]
@volkergersabeck decided to not integrate a feedback mail right now. So you can merge the PR as-is.

✅ &nbsp; I reviewed the changes, everything is as expected.

File: client/src/plugins/report-feedback/ClipboardCopySystemInfo.js [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+  }
+
+  _getVersion() {
+    return Metadata.data.version;
+  }
+
+  async _getOS() {
+    const os = await this._config.get('os.info');
+    return (PLATFORM_MAPPING[os.platform] || os.platform) +
+    '-' + os.release;
```
Comment (pinussilvestrus) [inline client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:69]: For MacOS, `os.release` actually retrieves the (Darwin) kernel version, not the actual macOS version.

image

So instead of macOS `11.5` (Big Sur), it would retrieve `20.6` for me. I don't know whether this is something we have to consider, but there are helpers to map these versions: https://github.com/sindresorhus/macos-release

File: client/src/plugins/report-feedback/ClipboardCopySystemInfo.js (hunk 1 above)
Comment (barmac) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js:36]: > Hm, well we could have the text in some transient hidden area and select and copy from there.

We don't need to do that. We can use asynchronous Clipboard API if we decide on the web way: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText

Comment (MaxTru) [reply client/src/plugins/report-feedback/ClipboardCopySystemInfo.js]: This is how `remote/clipboard#writeText` would/could look like: https://github.com/camunda/camunda-modeler/pull/2400/commits/453ff786d3befc5649f1eb6a796a0b907130ad39

**Comment by nikku** [comment]
I'll take over the review on this one.

File: client/src/plugins/index.js [hunk 3]
```diff
@@ -9,21 +9,23 @@
...
-import ErrorTracking from './error-tracking';
 import UsageStatistics from './usage-statistics';
-import ElementTemplatesModal from './element-templates-modal';
-import ZeebePlugin from './zeebe-plugin';
 import VersionInfo from './version-info';
+import ZeebePlugin from './zeebe-plugin';
 
 export default [
   CamundaPlugin,
+  ElementTemplatesModal,
```
Comment (nikku) [inline client/src/plugins/index.js:23]: I'm wondering if we should start to add eslint rules for this, if we sort variables often.

I've seen more and more fellows on our team doing it (sorting things).

**Review by nikku — APPROVED** [review]
Nice and clean.

The only feedback I have is that the feedback icon stands out a lot right now. I would love it to sit there a little smaller or muted, and less obtrusive I guess.

File: client/src/plugins/index.js (hunk 3 above)
Comment (nikku) [reply client/src/plugins/index.js:23]: Won't do it, as discussed.
