### PR TITLE
fix: set document title

### LINKED ISSUE #4376: Set window title via HTML
### What should we do?

Add title to the document to satisfy the a11y tool.

### Why should we do it?

We don't want the tool to complain; it's not an a11y problem because the title is set via a different API (Electron Browser Window).

Child of https://github.com/bpmn-io/internal-docs/issues/909

### PR DESCRIPTION
**Pull request by barmac**
image

Closes #4376

### Proposed Changes

This PR replaces the main process code used for the window title with an HTML `<title>` tag. The content is hard-coded as "Camunda Modeler" in contrast to the old solution where we added "(dev)" for dev mode, but this piece of information is already represented in the bottom-right "what's new" button. The main advantage of the current solution is that the a11y tools won't report missing title anymore.

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] **Brief textual description** of the changes present
* [ ] **Visual demo** attached
* [ ] **Steps to try out** present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: app/lib/index.js [hunk 1]
```diff
@@ -419,7 +419,6 @@ app.createEditorWindow = function() {
   const windowOptions = {
     resizable: true,
     show: false,
-    title: 'Camunda Modeler' + getTitleSuffix(app.metadata.version),
```
Comment (nikku) [inline app/lib/index.js:422]: I personally found this useful, why not keep it?

image

Comment (barmac) [reply app/lib/index.js:422]: It's a duplicate of 
image

Comment (barmac) [reply app/lib/index.js:422]: If we keep the code above, we set the title in two places:

1) main process
2) HTML

But on MacOS the HTML part takes precedence.

Comment (barmac) [reply app/lib/index.js:422]: Long term, we could consider adding context to the title, e.g. the current tab. But it's outside of the scope of the linked issue.

Comment (nikku) [reply app/lib/index.js:422]: OK, let's decide here and now that we ditch `dev` tag, and if we ever add it (again), then we do it inside the app.

**Review by nikku — APPROVED** [review]
