### PR TITLE
fix(tabs): show close on non active tabs until threshold width

### LINKED ISSUE #2639: In order to close a tab, I have to click/focus it first
__Describe the Bug__

In order to close a tab, I have to click/focus it first

__Steps to Reproduce__

1. Have two tabs open
2. Click on the second tab
3. Try to close the first tab without clicking on it / opening it first

__Expected Behavior__

I can close the tab without clicking it first. 

Why? Otherwise I need to always do 2 clicks

__Environment__

Camunda Modeler Nightly 15.12.2021

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #2639 

_Artifacts build [is running](https://github.com/camunda/camunda-modeler/runs/4701274691)_

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-win-x64.zip

Kapture 2022-01-03 at 14 54 26

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Since we fixed the notarization issue, I've added the artifacts for MacOS as well.

**Comment by pinussilvestrus** [comment]
I time-boxed creating test cases for properly setting the markers on resize, but getting stuck on properly handling the refs on mounting the functional components (cf. https://github.com/enzymejs/enzyme/issues/2215).

Also cf. on my comment I added on the last PR regarding the tab widths: https://github.com/camunda/camunda-modeler/pull/2589#issuecomment-984678992.

**Review by andreasgeier — APPROVED** [review]
Approved

File: client/src/app/primitives/__tests__/TabLinksSpec.js [hunk 1]
```diff
@@ -396,6 +396,53 @@ describe('<TabLinks>', function() {
     // in the current test environment
     it.skip('should set <small> selector on resize', function() {
 
+      // given
```
Comment (MaxTru) [inline client/src/app/primitives/__tests__/TabLinksSpec.js:399]: Since this test is skipped, do we need a dedicated issue describing what to do, in order to not skip such tests in the future anymore? (Could e.g., be something for spring cleaning)?

File: client/src/app/primitives/TabLinks.js [hunk 2]
```diff
@@ -33,7 +33,8 @@ const TABS_OPTS = {
   }
 };
 
-const SMALL_TAB_WIDTH = 45;
+const SMALL_TAB_WIDTH = 90;
+const SMALLER_TAB_WIDTH = 45;
```
Comment (MaxTru) [inline client/src/app/primitives/TabLinks.js:37]: (minor) `small` and `smaller` are confusing names I feel. Maybe it would simply help to add a comment here (or find better names, but I don't have any at hand)

**Review by MaxTru — COMMENTED** [review]
Nice!

I only have two minor comments, afterwards ready to merge IMO

File: client/src/app/primitives/__tests__/TabLinksSpec.js (hunk 1 above)
Comment (pinussilvestrus) [reply client/src/app/primitives/__tests__/TabLinksSpec.js:399]: I think we should follow the guideline here to not have refactoring issues in our backlog. I recently [time boxed this](https://github.com/camunda/camunda-modeler/pull/2655#issuecomment-1004893229) without a sufficient solution. The comments are there, next time somebody stumbles above it, one can again try to find something in a time-boxed manner.

File: client/src/app/primitives/TabLinks.js (hunk 2 above)
Comment (pinussilvestrus) [reply client/src/app/primitives/TabLinks.js:44]: I added a comment accordingly to achieve more clarity (couldn't find better names as well), https://github.com/camunda/camunda-modeler/pull/2655/commits/898f1ea4d67df6cf90d29716155c52c6989b7177.

File: client/src/app/primitives/__tests__/TabLinksSpec.js (hunk 1 above)
Comment (MaxTru) [reply client/src/app/primitives/__tests__/TabLinksSpec.js:399]: :+1:

File: client/src/app/primitives/TabLinks.js (hunk 2 above)
Comment (MaxTru) [reply client/src/app/primitives/TabLinks.js:44]: :+1:

**Review by MaxTru — APPROVED** [review]
