### PR TITLE
fix(client/plugins): add keyboard interaction trap to all plugin modals

### LINKED ISSUE #1692: Cannot use SPACE to check / uncheck check boxes in modals
__Describe the Bug__

As a standard browser behavior pressing `SPACE` toggles the value of a checkbox.

Our space-for-handtool feature built into the app seems to interfere with this and prevent `SPACE` for toggling to work:

capture GaQ9o7_optimized

_Imagine me pressing SPACE like crazy here._

This properly works in the properties panel (you can toggle via `SPACE` there).

__Steps to Reproduce__

* Create BPMN diagram
* Open privacy settings modal via menu
* Select checkbox
* Press `SPACE` in an attempt to toggle the checkbox via keyboard
* __See that nothing happens__

__Expected Behavior__

* With a modal dialog open, `SPACE` (like any other keyboard shortcut) is trapped inside the modal

__Environment__

- OS: Linux
- Camunda Modeler Version: v3.6.0

### PR DESCRIPTION
**Pull request by barmac**
Closes #1692

### CODE REVIEW

File: client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ import React, { PureComponent } from 'react';
 import PlayIcon from 'icons/Play.svg';
 
 import CamundaAPI from '../shared/CamundaAPI';
-import KeyboardInteractionTrap from '../shared/KeyboardInteractionTrap';
+import KeyboardInteractionTrap from '../../../app/primitives/modal/KeyboardInteractionTrap';
```
Comment (nikku) [inline client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js:16]: Can't we add the trap as a default to _all_ modals? It feels odd to me that every new modal has to add this for itself.

Comment (barmac) [reply client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js:16]: I was reluctant to do that because then we need to pass `triggerAction` to the modals. Yet, we can try this out.

**Comment by nikku** [comment]
Maybe that could be made available by the app via `React.Context`?

**Comment by barmac** [comment]
I'll try that out.

**Comment by barmac** [comment]
I've implemented the context-based solution and extracted the test refactoring to a separate PR: https://github.com/camunda/camunda-modeler/pull/1822

Please feel free to review now.

File: client/src/app/__tests__/AppSpec.js [hunk 2]
```diff
@@ -2643,6 +2645,12 @@ function createApp(options = {}, mountFn=shallow) {
 
   let app;
 
+  const flags = options.flags || {
+    [ DISABLE_REMOTE_INTERACTION ]: true
```
Comment (oguzeroglu) [inline client/src/app/__tests__/AppSpec.js:2649]: Why do we need this?

Comment (barmac) [reply client/src/app/__tests__/AppSpec.js:2649]: Without the flag we open privacy preferences in App tests :joy:

Comment (oguzeroglu) [reply client/src/app/__tests__/AppSpec.js:2649]: 🐵

Comment (barmac) [reply client/src/app/__tests__/AppSpec.js:2649]: image

File: client/src/app/App.js [hunk 3]
```diff
@@ -1809,155 +1810,159 @@ export class App extends PureComponent {
 
         <div className={ css.App }>
 
-          <SlotFillRoot>
+          <KeyboardInteractionTrapContext.Provider value={ this.triggerAction }>
```
Comment (oguzeroglu) [inline client/src/app/App.js:1813]: Maybe I'm missing the point here but is there a reason why we don't only wrap PluginsRoot component? AFAIK KeyboardInteractionTrap was meant to be used by plugins.

Comment (barmac) [reply client/src/app/App.js:1813]: It's meant to be used by modals, regardless of whether they are embedded in plugins or not. The benefit of the `KeyboardInteractionTrap` is that you don't accidentally activate editor's shortcuts while a modal is open. Also, there is still one modal which has not been moved to the plugins yet: KeyboardShortcuts. Therefore, I don't see reason to limit the scope of the context.

File: client/src/app/primitives/modal/Modal.js [hunk 4]
```diff
@@ -60,14 +61,16 @@ export default class Modal extends PureComponent {
     } = this.props;
 
     return ReactDOM.createPortal(
-      <div className="modal" tabIndex="-1" role="dialog">
-        <div className={ classNames('modal-dialog', className) } ref={ this.modalRef } role="document">
-          <div className="modal-content">
-            { children }
-            { onClose && (<Close onClick={ this.close } />) }
+      <KeyboardInteractionTrap>
```
Comment (nikku) [inline client/src/app/primitives/modal/Modal.js:64]: Really good solution! Thanks :clap:

Comment (barmac) [reply client/src/app/primitives/modal/Modal.js:64]: Thanks :)
