### PR TITLE
deps: update to `@camunda/task-testing@0.2.6`

### LINKED ISSUE #5298: Input variables editor disappears when content is erased
### Describe the bug

https://github.com/user-attachments/assets/b3370cbf-4eb2-4e65-87cb-0b1b9e737c4d

### Steps to reproduce

1. Erase content of task testing input variables
3. now this happens

### Expected behavior

Editor should stay.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: 5.40.0-rc.0
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### LINKED ISSUE #5299: Task testing element type misses element template name
### Describe the bug

It should display REST Outbound Connector and not Service Task

Image

### Steps to reproduce

1. Select a templated element
2. Open task testing
3. now this happens

### Expected behavior

Use the same name as in the properties panel.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

Closes #5298
Closes #5299
 

### Checklist

To ensure you provided everything we need to look at your PR:

* [ ] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [ ] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
I can reproduce the CI errors, so it's more than a dependency update.

File: client/src/app/panel/tabs/task-testing/__tests__/TaskTestingTabSpec.js [hunk 1]
```diff
@@ -157,15 +161,14 @@ describe('<TaskTestingTab>', function() {
...
-
       // when
       modeler.get('selection').select(modeler.get('elementRegistry').get('Task_1'));
+      await clock.tickAsync(CONNECTION_CHECKER_INTERVAL);
 
-      // then
-      await waitFor(() => {
-        expect(getByText(UNSUPPORTED_EXECUTION_PLATFORM_VERSION_TITLE)).to.exist;
-      });
+      // expect
```
Comment (jarekdanielak) [inline client/src/app/panel/tabs/task-testing/__tests__/TaskTestingTabSpec.js]:
```suggestion
      // then
```
