### PR TITLE
fix: set explicitly `useTLS=false` for http endpoints

### LINKED ISSUE #3152: Desktop Modeler fails to deploy to self-managed Cluster with Identity (415, Unsupported Media Type)
### Describe the bug

After setting the deployment parameters for self-managed and oAuth, the deployment fails. The Modeler log shows:
01:39:00,341 WARN  [org.keycloak.events] (default task-11) type=LOGIN_ERROR, 

> 2022-09-23T05:46:55.716Z  ERROR app:zeebe-api Failed to connect with config (secrets omitted): {
>   endpoint: {
>     type: 'oauth',
>     url: '127.0.0.1:26500',
>     clientId: 'java',
>     oauthURL: 'http://127.0.0.1:18080/auth/realms/camunda-platform/protocol/openid-connect/token'
>   }
> } GotError [HTTPError]: Response code 415 (Unsupported Media Type)
>     at EventEmitter.<anonymous> (C:\tools\camunda-modeler\resources\app.asar\node_modules\got\source\as-promise.js:74:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:96:5) {
>   host: '127.0.0.1:18080',
>   hostname: '127.0.0.1',
>   method: 'POST',
>   path: '/auth/realms/camunda-platform/protocol/openid-connect/token',
>   socketPath: undefined,
>   protocol: 'http:',
>   url: 'http://127.0.0.1:18080/auth/realms/camunda-platform/protocol/openid-connect/token',
>   gotOptions: {
>     path: '/auth/realms/camunda-platform/protocol/openid-connect/token',
>     protocol: 'http:',
>     slashes: true,
>     auth: null,
>     host: '127.0.0.1:18080',
>     port: '18080',
>     hostname: '127.0.0.1',
>     hash: null,
>     search: null,
>     query: null,
>     pathname: '/auth/realms/camunda-platform/protocol/openid-connect/token',
>     href: 'http://127.0.0.1:18080/auth/realms/camunda-platform/protocol/openid-connect/token',
>     retry: {
>       retries: [Function (anonymous)],
>       methods: [Set],
>       statusCodes: [Set],
>       errorCodes: [Set]
>     },
>     headers: {
>       'user-agent': 'zeebe-client-nodejs/2.4.0',
>       'content-type': 'application/json',
>       'accept-encoding': 'gzip, deflate',
>       'content-length': 128
>     },
>     hooks: {
>       beforeRequest: [],
>       beforeRedirect: [],
>       beforeRetry: [],
>       afterResponse: [],
>       beforeError: [],
>       init: []
>     },
>     decompress: true,
>     throwHttpErrors: true,
>     followRedirect: true,
>     stream: false,
>     form: false,
>     json: false,
>     cache: false,
>     useElectronNet: false,
>     body: '{"audience":"127.0.0.1","client_id":"java","client_secret":"5N1lW0ykk7UgVyaL1g1oV5a72Yigdz5V","grant_type":"client_credentials"}',
>     method: 'POST'
>   },
>   statusCode: 415,
>   statusMessage: 'Unsupported Media Type',
>   headers: {
>     'x-xss-protection': '1; mode=block',
>     'x-frame-options': 'SAMEORIGIN',
>     'referrer-policy': 'no-referrer',
>     date: 'Fri, 23 Sep 2022 05:46:55 GMT',
>     connection: 'close',
>     'strict-transport-security': 'max-age=31536000; includeSubDomains',
>     'x-content-type-options': 'nosniff',
>     'content-type': 'application/json',
>     'content-length': '55'
>   },
>   body: '{"error":"RESTEASY003065: Cannot consume content type"}'
> }

It seems worth noting that the client id her does not reflect the the Id entered in the modeler ("java") and the auth_type may need to be "client credentials" instead of code.

Authentication from curl or Postman works, e.g:

curl --location --request POST 'http://localhost:18080/auth/realms/camunda-platform/protocol/openid-connect/token' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'client_id=java' --data-urlencode 'client_secret=xyz' --data-urlencode 'grant_type=client_credentials'
{"access_token":"shortened-it_works","expires_in":300,"refresh_expires_in":0,"token_type":"Bearer","not-before-policy":0,"scope":"profile email"}

### Steps to reproduce

1. Try to deploy a process model from Desktop modeler to a self-managed Camunda 8 with Identity enabled
2. notice error message can check modeler log

### Expected behavior

Deployment succeeds if parameters are set correctly.
Meaningful connection or authentication error is shown if parameters are incorrect (not "unknown error")

### Environment

- win 11
- Camunda Modeler Version: 5.3.0
- Execution Platform:  https://github.com/rob2universe/camunda-8-helm-profiles/tree/dev-identity/dev-identity

### Additional context

_No response_

----

Related to SUPPORT-14704

### PR DESCRIPTION
**Pull request by barmac**
* [x] Verified to work with oAuth + http
* [x] Verified to work with C8 SaaS
* [x] Verified to work with no auth + http

Closes #3152

### CODE REVIEW

File: app/test/spec/zeebe-api-spec.js [hunk 1]
```diff
@@ -1495,7 +1495,67 @@ describe('ZeebeAPI', function() {
...
+
+      // when
+      await zeebeAPI.deploy(parameters);
+
+      // then
+      expect(usedConfig[1]).to.have.property('useTLS', false);
+    });
+
+
+    it('should set NOT `useTLS=false` for no protocol endpoint (cloud)', async () => {
```
Comment (nikku) [inline app/test/spec/zeebe-api-spec.js:1532]:
```suggestion
    it('should set `useTLS=true` for no protocol endpoint (cloud)', async () => {
```

**Comment by barmac** [comment]
Artifacts will be available at:

- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth/camunda-modeler-3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth/camunda-modeler-3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth/camunda-modeler-3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth/camunda-modeler-3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth/camunda-modeler-3152-make-it-possible-to-deploy-to-unsecured-local-cluster-with-oauth-win-x64.zip

**Comment by barmac** [comment]
@rob2universe If you want to give it a try before it lands on nightly, feel free to use the links above (should be ready in ~20 minutes).
