### PR TITLE
Fix Switching Tabs With Unsaved Changes

### LINKED ISSUE #1347: Unsaved Changes Lost When Switching Back and Forth between Tabs
__Description__

When I open a new diagramm the changes in my first diagramm are undone.
**All diagramms** that are opened in XML View are reloaded  and all changes are removed.

__Steps to Reproduce__

1. Open a diagramm (or create a diagramm)
2. Change something in the diagramm
3. Switch to XML View of the diagramm
4. Create a new diagramm (File -> new File -> ... or Cntl +T have the same effect)
5. Go back to the first diagramm (all changes are undone)

__Expected Behavior__

When I open a new diagramm the other diagrammes should not be changed.

__Environment__

- Windows 10
- Modeler 3.0
- Plugin: camunda-modeler-property-info-plugin

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #1347

### CODE REVIEW

File: client/src/app/tabs/MultiSheetTab.js [hunk 1]
```diff
@@ -315,31 +315,16 @@ export class MultiSheetTab extends CachedComponent {
   }
 
   componentDidMount() {
-    const {
```
Comment (nikku) [inline client/src/app/tabs/MultiSheetTab.js]: Seems like we are going back and forth here.

Could you verify that the bug fix that introduced this change (if one exists, check `git blame`) is still fixed when removing that line?
