### PR TITLE
fix(client/App): de-curry tab callback handlers

### LINKED ISSUE #5748: Desktop Modeler 5.45.0 tab crashes when opening BPMN
### Describe the bug

After updating Desktop Modeler to version 5.45.0 (on Windows) it often happens that the tab crashes when opening a BPMN file.
It's not always happening, but for me the majority of files opened is showing this issue.

The tab in this case displays "Ooops, this shouldn't have happened. This tab crashed due to an unexpected error."
The output log shows `Minified React error #185;`:
```
at Error (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:265:248)
    at gi (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:182:224)
    at enqueueSetState (webpack://camunda-modeler-client/node_modules/react/cjs/react.production.min.js:12:236)
    at setState (webpack://camunda-modeler-client/src/app/slot-fill/SlotFillRoot.js:50:13)
    at addFill (webpack://camunda-modeler-client/src/app/slot-fill/Fill.js:67:16)
    at _register (webpack://camunda-modeler-client/src/app/slot-fill/Fill.js:46:9)
    at componentDidUpdate (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:260:315)
    at kk (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:259:445)
    at ik (webpack://camunda-modeler-client/node_modules/react-dom/cjs/react-dom.production.min.js:258:430)
    at file:///C:/Users/***/***/CamundaModeler/resources/app.asar/public/bundle.js:179:1075543 [ error ]
```
Just closing the tab and re-opening the file or switching to another open tab and going back to the crashed one shows the BPMN correctly.

Also opening files by dragging them on Modeler seems to not cause any problems.

Other members from my team are experiencing the same.

### Steps to reproduce

1. Open a BPMN file in Desktop Modeler 5.45.0 by double-clicking on the file in Windows Explorer.
2. The tab opens in Modeler with the message "Ooops, this shouldn't have happened. This tab crashed due to an unexpected error." instead of showing the BPMN.

### Expected behavior

1. Open a BPMN file in Desktop Modeler 5.45.0 by double-clicking on the file in Windows Explorer.
2. The tab opens in Modeler and is showing the BPMN diagram.

### Environment

- OS: Windows 11 Enterprise
- Camunda Modeler Version: 5.45.0
- Execution Platform: Camunda 8
- Installed plug-ins: none

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philippfromme**
### Proposed Changes

Removes unnecessary currying from handleTabChanged, handleTabError, handleTabWarning, handleTabShown to ensure stable function references across renders.

Currying was introduced here: https://github.com/camunda/camunda-modeler/commit/ec0b1d1b6523f9ef406820306b8a5a0279607028

Fixes infinite re-render loop when opening files via OS double-click after React 18 migration.

Closes #5748

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [x] Pull request __establishes context__
  * [x] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [ ] __Screenshots or short videos__ showing UI/UX changes
  * [ ] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

**Comment by philippfromme** [comment]
To the reviewers: Please run the modeler and try to break it. I cannot reproduce the issue anymore on my machine.

**Comment by barmac** [comment]
Current implementation makes sure that the tab calling `onChange` etc. does not trigger execution with another tab. So if tab X called `onChange`, it was called with tab X as the argument. If we merge this as-is, we may encounter a problem that a tab X triggers a call of `handleTabChanged` but the `activeTab` is Y, so the callback is executed for another tab with the tab X's arguments. So perhaps a safe choice would be to ensure stable references but with keeping the tab-bound nature of the passed callbacks.
The current architecture allows (or at least aims) to decouple the tab updates from the active tab. It will be more difficult if we accept the change as-is.

**Comment by barmac** [comment]
So an alternative solution could look like https://github.com/camunda/camunda-modeler/pull/5775

**Comment by philippfromme** [comment]
@barmac That was the first solution I implemented, too. But then I was wondering why currying is necessary in the first place. Do you remember if we had the issues you describe at any point? I don't remember why we introduced currying.

**Comment by barmac** [comment]
The point of the code is to solve cases like below correctly:

image

Do we actually make use of this property? I don't know, though at least for handleTabShown we active prevent non-active tab call: https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/App.js#L971

**Comment by jarekdanielak** [comment]
@barmac heads up, in the example you linked the `activeTab` is not actually guaranteed to be up-to-date in a race-condition scenario. Especially after we've moved up to React 18, we should only rely on the state derived from the `setState`:

```js
this.setState((state) => {
  const { openedTabs, activeTab, tabShown } = state;

  /// do stuff
});
```

**Comment by philippfromme** [comment]
@barmac In your example tab X can call `onChanged` at a point where it's not the active tab anymore. What I'm asking myself is if this is even possible? The worst case with the implementation in this PR is that e.g. `handleTabChanged` is called by tab X but will execute with tab Y which is the new active tab. If we want to discard callback calls by non-active tabs we either have to let the tab call the callback with itself (e.g. `onChanged(this.props.tab, ...)` instead of `onChanged(...)`) as it was before the currying or combine currying and cashing. In both cases we'd have to explicitly discard callback calls in all affected methods.

**Comment by philippfromme** [comment]
@barmac @jarekdanielak So what solution should we go for? 🤔

**Comment by barmac** [comment]
If this solution fixes the problem and does not create new ones, let's go for it. I just want to avoid a situation where we fix and break the experience at the same time by removal of [the Chesterton's fence](https://fs.blog/chestertons-fence/).

**Comment by jarekdanielak** [comment]
Let's simplify. Introducing custom caching inside of a React component doesn't seem right. React does a lot under the hood, it's going to bite us back if we overengineer. I think the bug we're fixing is a good example.

**Comment by philippfromme** [comment]
@nikku Maybe you remember why we introduced currying back then.

**Comment by philippfromme** [comment]
The currying could protect against a very narrow race condition with async callbacks from dying editors, but there's no evidence it was introduced for that reason. If we want to be extra safe, we could add a guard like `if (this._unmounted) return;` in the editors. The responsibility would shift: instead of the parent (App) defensively binding the tab through currying to handle stale callbacks, each editor would simply not call callbacks after unmounting. That's the more standard React pattern where components are responsible for cleaning up their own async work. We actually have that already: https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/BpmnEditor.js#L143 We're just not using it consistently.

File: client/src/app/App.js [hunk 1]
```diff
@@ -951,25 +953,17 @@ export class App extends PureComponent {
...
   /**
-   * Mark a tab as shown.
-   *
-   * @param {Object} tab descriptor
-   *
-   * @return {Function} tab shown callback
+   * Mark the active tab as shown.
    */
-  handleTabShown = (tab) => () => {
+  handleTabShown = () => {
```
Comment (nikku) [inline client/src/app/App.js]: I recommend we still pass _the tab_ explicitly here. Otherwise what tab is shown? If it always is the one in the promise, then the method should probably be called `handleActiveTabShown`.

File: client/src/app/App.js [hunk 2]
```diff
@@ -983,42 +977,37 @@ export class App extends PureComponent {
...
    *
-   * @param {Object} tab descriptor
-   *
-   * @return {Function} tab error callback
+   * @param {Error} error
    */
-  handleTabError = (tab) => (error) => {
-    this.handleError(error, tab);
+  handleTabError = (error) => {
+    this.handleError(error, this.state.activeTab);
```
Comment (nikku) [inline client/src/app/App.js:993]: Cf. https://github.com/camunda/camunda-modeler/pull/5774/changes#r2987148943

Comment (nikku) [reply client/src/app/App.js:993]: In the past, different tabs were able to report issues - this is no longer the case with this change.

File: client/src/app/App.js [hunk 3]
```diff
@@ -2409,10 +2398,10 @@ export class App extends PureComponent {
                         tab={ activeTab }
                         layout={ layout }
                         linting={ this.getLintingState(activeTab) }
-                        onChanged={ this.handleTabChanged(activeTab) }
-                        onError={ this.handleTabError(activeTab) }
-                        onWarning={ this.handleTabWarning(activeTab) }
-                        onShown={ this.handleTabShown(activeTab) }
+                        onChanged={ this.handleTabChanged }
```
Comment (nikku) [inline client/src/app/App.js:2420]: Needs to be fixed - but see also linting above - that also needs to be fixed:

```
                        linting={ this.getLintingState(activeTab) }
```

In the React world, this has to be a memoized function (no currying) or the solution above sketched in this PR.

Comment (nikku) [reply client/src/app/App.js:2420]: After a second thought - `linting={ this.getLintingState(activeTab) }` looks odd, but could be just fine - if the result is stable across re-renders.

File: client/src/app/App.js [hunk 4]
```diff
@@ -1055,7 +1044,7 @@ export class App extends PureComponent {
   };
 
   getLintingState = (tab) => {
-    return this.state.lintingState[ tab.id ] || [];
+    return this.state.lintingState[ tab.id ] || EMPTY_LINTING_STATE;
```
Comment (nikku) [inline client/src/app/App.js:1066]: ⭐

**Comment by philippfromme** [comment]
I've added https://github.com/camunda/camunda-modeler/pull/5774/commits/ea04f3c0fa3683262658c9e27bc26f45176c4879 as an example of shifting the responsibility to the editors but it's quite easy to forget about it. 🤔

File: client/src/app/App.js (hunk 1 above)
Comment (philippfromme) [reply client/src/app/App.js]: That's what we did before the currying. So we'd just revert entirely then. Would be fine with me.

File: client/src/app/App.js (hunk 3 above)
Comment (philippfromme) [reply client/src/app/App.js:2420]: This should be stable between renders thanks to the call returning `return this.state.lintingState[ tab.id ] || EMPTY_LINTING_STATE;`. 🤔

**Comment by barmac** [comment]
> I've added [ea04f3c](https://github.com/camunda/camunda-modeler/commit/ea04f3c0fa3683262658c9e27bc26f45176c4879) as an example of shifting the responsibility to the editors but it's quite to forget about it. 🤔

If we want to drop the callbacks right after the tab is unmounted, I think the safest choice would be to either introduce the comparisons (`tab === activeTab`) in the handlers, or wrap the Tab component from the Tabs provider in a component which performs that check. Moving the responsibility to editors makes it so easy to introduce a problem.

File: client/src/app/App.js (hunk 1 above)
Comment (barmac) [reply client/src/app/App.js]: Given that the `Tab` component gets the tab anyway, it could indeed call the handlers with the tab. So that would ensure we keep the behavior as is today. Cf. also https://github.com/camunda/camunda-modeler/pull/5774#issuecomment-4125416793

**Comment by philippfromme** [comment]
Agreed. So we'll make the tabs pass themselves as the caller when calling a callback. The handlers in the app will check if it's the active tab and ignore if not. Correct?

**Comment by nikku** [comment]
> So we'll make the tabs pass themselves as the caller when calling a callback. 

Yes, that is an option.

**Comment by philippfromme** [comment]
Okay, I think this is good enough for now:

* removed currying
* tabs passed to callbacks
* callbacks will return early if tab not active tab

Basically reverting to pre-2019 state. 😆

File: client/src/app/App.js (hunk 2 above)
Comment (philippfromme) [reply client/src/app/App.js:993]: But was this by accident or intended? By definition there can only be a single active tab at a time. Should we expect callbacks called from an unmounted tab?

File: client/src/app/App.js (hunk 4 above)
Comment (philippfromme) [reply client/src/app/App.js:1066]: 🤗

File: client/src/app/App.js (hunk 2 above)
Comment (nikku) [reply client/src/app/App.js:993]: > Should we expect callbacks called from an unmounted tab?

I think today, we should not. In the future we may (i.e. for async validation).

Comment (nikku) [reply client/src/app/App.js:993]: Especially for errors - I'd not swallow them but always log.
