### PR TITLE
fix(dmn): enable backspace in literalExpressions editor

### LINKED ISSUE #2095: Deleting with backspace is not possible if a literal expression was reopened
__Describe the Bug__

I want to open and edit a DMN file that already contains a Literal Expression task. After choosing the task in the DRD and click at the end of the expression line (or any other point in it) and than pressing backspace, the last char will not removed and an exception is printed in the log. If I press any other key, like delete or letters, the expression can be edited and even backspace will work after pressing any other key.

The exception from the log:
```
removeSelection is not a registered action
    at Th (webpack:///node_modules/dmn-js-literal-expression/lib/features/editor-actions/EditorActions.js:126:9)
    at e.value (webpack:///node_modules/dmn-js-literal-expression/lib/features/editor-actions/EditorActions.js:48:14)
    at trigger (webpack:///src/app/tabs/dmn/DmnEditor.js:669:7)
    at triggerAction (webpack:///src/app/tabs/MultiSheetTab.js:258:18)
    at triggerAction (webpack:///src/app/tabs/EditorTab.js:36:33)
    at triggerAction (webpack:///src/app/App.js:1709:15)
    at fn (webpack:///src/app/App.js:2232:19)
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:109443
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:109519
    at file:///D:/Programme/camunda-modeler-4.6.0-win-x64/resources/app.asar/public/bundle.js:65:122809 [ error ]
```

__Steps to Reproduce__

1. Get a DMN file with at least one LiteralExpression
2. (Re-)open the DMN file. Select the LiteralExpression, so that you can edit the actual expression.
3. When clicking in or at the end of the expression line and trying to delete parts of it with the backspace key, an exception appears in the log and no char is deleted.

__Expected Behavior__

Backspace should not lead to excpetions and it should delete the char before the cursor.

__Environment__

- OS: [Windows 10, Ubuntu 18]
- Camunda Modeler Version: [reproduced in 4.4 and 4.6]

image

----

Related to [SENTRY issues](https://sentry.io/organizations/camunda-modeling/issues/?groupStatsPeriod=auto&project=5223041&query=removeSelection&statsPeriod=14d).

### PR DESCRIPTION
**Pull request by marstamm**
Root cause: The literalExpressions editor does not fire events when elements are selected, so `inputActive` is not set correctly.

As introducing these events would be a bigger refactoring and the action should never be performed without `role: delete`, I decided to fix it in the modeler by setting `inputActive` to true. 

closes #2095

### CODE REVIEW

File: client/src/app/tabs/dmn/DmnEditor.js [hunk 1]
```diff
@@ -391,7 +391,8 @@ export class DmnEditor extends CachedComponent {
         defaultCopyCutPaste: true,
         defaultUndoRedo: true,
         removeSelected: true,
-        selectAll: true
+        selectAll: true,
+        inputActive: true
```
Comment (nikku) [inline client/src/app/tabs/dmn/DmnEditor.js:395]: I believe if we go for such a hack we should properly document it in the source code, i.e. by providing a link back  to the PR.

It would otherwise cost us a considerable amount some time to understand why `inputActive` has to be there in the first place.

**Review by nikku — COMMENTED** [review]
Works well. Happy to merge it if we leave a hint why `inputActive` works as intended, in the source code.

File: client/src/app/tabs/dmn/DmnEditor.js (hunk 1 above)
Comment (marstamm) [reply client/src/app/tabs/dmn/DmnEditor.js]: Done :heavy_check_mark:

**Review by nikku — APPROVED** [review]
