### PR TITLE
fix(VersionInfo): update release notes link

### LINKED ISSUE #3655: Broken link for "Release Notes on Camunda Blog"
### Describe the bug

Appears to be a broken link when clicking on **"Release Notes on Camunda Blog"** 

image

Getting 404 after redirecting to this url: 
https://camunda.com/blog/category/modeling/?tag=camunda-modeler&release-note&utm_source=modeler&utm_medium=referral

image

### Steps to reproduce

1. Open a recent version of the Camunda Modeler
2. On the bottom right, click on the version number (eg: 5.11.0)
3. A summary of new changes are displayed. Click on **Release Notes on Camunda Blog** hyperlink.
4. A new browser page opens up, but returns 404 error.

### Expected behavior

Release Notes of the current version should be displayed (eg: 5.11.0 release notes)

## Camunda Modeler system information
 * Version: 5.11.0
 * Operating System: Windows 10 amd64
 * Plugins: <no plugins>
 * Execution Platform: BPMN - Camunda Platform 7

### Additional context

Here is another URL that is somewhat close to what might work - 
https://camunda.com/blog/category/releases/?s=modeler
or the changelog...
https://github.com/camunda/camunda-modeler/blob/develop/CHANGELOG.md#5110

### PR DESCRIPTION
**Pull request by smbea**
Closes #3655

### CODE REVIEW

**Review by nikku — APPROVED** [review]

File: client/src/plugins/version-info/VersionInfoOverlay.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ import { Overlay, Section } from '../../shared/ui';
 
 import { ReleaseInfo } from './ReleaseInfo';
 
-const RELEASE_NOTES_LINK = 'https://camunda.com/blog/category/modeling/?tag=camunda-modeler&release-note&utm_source=modeler&utm_medium=referral';
+const RELEASE_NOTES_LINK = 'https://camunda.com/blog/category/releases/?s=desktop+modeler';
```
Comment (marstamm) [inline client/src/plugins/version-info/VersionInfoOverlay.js:17]: Seems like the old link redirects to `https://camunda.com/blog/category/releases/?tag=camunda-modeler` instead of `camunda-modeler`. Is this difference relevant for us?

Comment (barmac) [inline client/src/plugins/version-info/VersionInfoOverlay.js:17]: Let's not remove marketing query params:
```suggestion
https://camunda.com/blog/category/releases/?s=desktop+modeler&utm_source=modeler&utm_medium=referral
```

Comment (smbea) [reply client/src/plugins/version-info/VersionInfoOverlay.js:17]: Well, technically there is Camunda Web Modeler and Camunda Desktop Modeler. There isn't really blog posts on web modeler so it works out but it's just safer to use desktop modeler

Comment (smbea) [reply client/src/plugins/version-info/VersionInfoOverlay.js:17]: I will add this back

Comment (nikku) [reply client/src/plugins/version-info/VersionInfoOverlay.js:17]: :+1:
