### PR TITLE
fix: update tab with new attributes

### LINKED ISSUE #2581: Form file name not displayed
__Describe the Bug__

When saving a freshly created form file the new file name is not displayed in the tab bar. Instead of that the initial file name `form_1.form`  is displayed.
Furthermore the tooltip shows `unsaved` when I hover over the tab header. 

__Steps to Reproduce__

1. create a new form file
2. save it and change the file name 
3. observe the displayed file name in the tab header
4. hover over the tab header

__Expected Behavior__

correct file name will be displayed

__Environment__

- OS:  linux mint 20.2
- Camunda Modeler Version: 4.11.1-new-properties-panel edition

### PR DESCRIPTION
**Pull request by smbea**
Closes #2581

Explanation: the spread operator only keeps the enumerable properties of the object itself. Therefore, functions like `getTitle()` were getting lost.

### CODE REVIEW

**Review by MaxTru — COMMENTED** [review]
Great!

Maybe use our utility function for `assign`?
https://github.com/camunda/camunda-modeler/pull/2649/commits/e92bf615c55d7abd86874b846bade995a26919bd#diff-b650ad882ccc34a87aa822cb69b9bffc2e3c1513db7dbdff0fc8aaec11fd99a2L16

Otherwise we have two different `assign` usage approaches even within the same source code file.

**Comment by barmac** [comment]
Can you please provide a test case so that we catch the bug if it reappears?

**Comment by smbea** [comment]
I added new changes because, as it turns out, that using `assign` still causes the loss of the getters, when trying to clone a tab object. I added a `cloneWithDescriptors` function which clones an object, keeping the getters/setters of the properties. Once this is done, then we can assign the new attributes:

```javascript 
let updatedTab = cloneWithDescriptors(tab);
assign(updatedTab, newAttrs);
```

I also added a test case to ensure this stays functional.

This was the simplest solution I found for this issue. Let me know what you think.

**Comment by MaxTru** [comment]
LGTM. I will not approve because I want to give @barmac opporunity to review as well

File: client/src/app/__tests__/AppSpec.js [hunk 1]
```diff
@@ -2177,7 +2193,6 @@ describe('<App>', function() {
       } = app.state;
 
       // then
-      expect(updatedTab).to.not.eql(tab);
```
Comment (MaxTru) [inline client/src/app/__tests__/AppSpec.js:2180]: Why is this needed? Does this even make sense?

Comment (smbea) [reply client/src/app/__tests__/AppSpec.js:2180]: I missed the line that made this make sense. Here it is:
 
 ```diff

-  expect(updatedTab).to.not.eql(tab);
+  expect(updatedTab).to.include(newAttrs);

```
This was causing the test to fail. Even with the new function I added, the old tab object is updated with the new properties. I'm not sure how we can prevent this from happening easily.

I didn't consider assertion relevant, because the "navigation history" test passes, and the new tab is updated correctly (as proved by the new line added).

But let me know if you have different insight on this.

File: client/src/app/__tests__/AppSpec.js [hunk 2]
```diff
@@ -2139,6 +2139,22 @@ describe('<App>', function() {
...
+    it('should update with attributes getters', async function() {
+
+      // given
+      const tab = await app.createDiagram('form');
+
+      // when
+      const updatedTab = await app.triggerAction('lint-tab', { tab });
+
+      const nameGetter = Object.getOwnPropertyDescriptor(updatedTab, 'name').get;
+      const titleGetter = Object.getOwnPropertyDescriptor(updatedTab, 'name').get;
```
Comment (barmac) [inline client/src/app/__tests__/AppSpec.js:2151]: This is super low-level. I'd rather expect just a check if the tab name and title are correct (value test).

**Comment by barmac** [comment]
I was just wondering... How about if we use [`TabsProvider#createForFile`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/TabsProvider.js#L461) to create a new tab from the same file and then just make sure we properly clone the ID and update the properties? This way we could perhaps avoid the problem of cloning the descriptors.

**Comment by smbea** [comment]
> I was just wondering... How about if we use TabsProvider#createForFile to create a new tab from the same file and then just make sure we properly clone the ID and update the properties? This way we could perhaps avoid the problem of cloning the descriptors.

The reason for that is because that would generate a different ID, and would not work with this:

```javascript
// replace activeTab
let updatedActiveTab = activeTab;
if (activeTab.id === updatedTab.id) {
    updatedActiveTab = updatedTab;
}
```

**Comment by barmac** [comment]
True, but we can just keep the old id, right?
```javascript
const newTab = tabsProvider.createTabForFile(oldTab.file);
newTab.id = oldTab.id;
```

**Comment by smbea** [comment]
That works and ridiculously simpler 😂

**Comment by barmac** [comment]
https://user-images.githubusercontent.com/28307541/147125666-af38e5d2-d5cf-4118-98b9-f1fec6316c52.mov

Hmm the new solution introduces a new bug which is uncaught on the CI :/

**Comment by barmac** [comment]
(My comment was about the state before your most recent push).

**Comment by smbea** [comment]
> (My comment was about the state before your most recent push).

I only simplified the test case in the most recent push

**Comment by smbea** [comment]
I will put this on hold for now and come back to it in January

**Comment by smbea** [comment]
It appears that the bug that @barmac noticed, is also present on develop so it isn't introduced by this fix. I created an issue for this: https://github.com/camunda/camunda-modeler/issues/2654

**Review by MaxTru — APPROVED** [review]
:wave:
