### PR TITLE
Display context of tab in log

### LINKED ISSUE #1176: Tab errors don't provide relevant context
__Describe the Bug__

In the old version of the Camunda Modeler (v2.x) errors logged in the log panel would provide the relevant context (the file displayed in the tab that reported the error).

In the new version of the Modeler (v3) we simply display the error messages without providing the relevant context:

image

__Steps to Reproduce__

* Open BPMN diagram
* _break it via XML tab_
* Import again
* See error message being logged without context information

__Expected Behavior__

* Error messages are logged with the relevant context attached:

    ```
    { path to displayed / opened file}
    { error messages }
    ```

__Environment__

Please complete the following information:

 - OS: Any
 - Camunda Modeler Version: 3.0.0-0

### PR DESCRIPTION
**Pull request by barmac**
Closes #1176

### CODE REVIEW

File: client/src/app/AppParent.js [hunk 1]
```diff
@@ -259,6 +267,39 @@ export default class AppParent extends PureComponent {
...
+   */
+  logToClient(category, errorLike, tab) {
+    const entry = this.getLogEntry(category, errorLike.message, tab);
+
+    this.triggerAction(null, 'log', entry);
+  }
+
+  getLogEntry(category, message, tab) {
+    if (tab) {
+      message = `[${tab.file.name}] ${message}`;
```
Comment (nikku) [inline client/src/app/AppParent.js]: Why don't we log the full file path, if it is available to us? It can happen that files are named exactly the same but have very different contents.

File: client/src/app/AppParent.js [hunk 2]
```diff
@@ -292,12 +290,33 @@ export default class AppParent extends PureComponent {
...
+    const entry = {
+      message: this.getEntryMessage(error.message, tab),
+      stack: error.stack
+    };
+
+    return entry;
+  }
+
+  getEntryMessage(message, tab) {
+    return tab ? `[${tab.file.name}] ${message}` : message;
```
Comment (nikku) [inline client/src/app/AppParent.js]: Let's log the full file path, if available here, too.

And handle the case that a tab does not have a referenced file (empty tab or some extension tab)

**Comment by barmac** [comment]
To do:
1) check if we can use source maps to track down the exact line where error occurred

**Comment by barmac** [comment]
Source map parsing makes the stuff async and this breaks tests. I'm going to fix this after weekend.
