### PR TITLE
fix(start instance): close overlay through icon click

### LINKED ISSUE #3052: "Start instance" button doesn't close overlay on second click
### Describe the bug

The start instance icon button on the status bar doesn't behave as expected.

### Steps to reproduce

1. Click on the play icon in the status bar -> overlay opens
2. Click icon again -> nothing happens 

### Expected behavior

The overlay should close on the second click to match the behaviour of the other status bar overlays.

### Environment

- Camunda Modeler Version: 5.1
- Execution Platform: Camunda Platform 7 and 8 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by smbea**
Closes #3052

Note: These files were a bit confusing so I did some clean-up along with the solution

### CODE REVIEW

File: client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js [hunk 1]
```diff
@@ -179,6 +179,12 @@ export default class StartInstanceTool extends PureComponent {
        !deployService.canDeployWithConfiguration(deploymentConfig) ||
        await this.checkConnection(deploymentConfig.endpoint);
 
+     this.setState({ overlayState: {
+       handleClose: () => {
+         deployService.closeOverlay();
+       }
+     } });
```
Comment (pinussilvestrus) [inline client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js:186]: Due to missing context: Can you explain why we need to set such a close handler to the state?

**Comment by pinussilvestrus** [comment]
Do we have the same problem with C8? As I can't close the overlay via icon-click
Bildschirmfoto 2022-08-16 um 16 41 55

**Review by pinussilvestrus — APPROVED** [review]
Works like a charm, and thanks for the follow-up 👍 

✅
