### PR TITLE
Downscale images if cannot be generated

### LINKED ISSUE #1591: Modeler PNG export does not create a valid PNG
__Describe the Bug__

The Camunda Modeler does not create a valid PNG for the attached BPMN-file. The PNG file is created but you get an error when you want to open it (0 kb file).

__Steps to Reproduce__

1. Open BPMN diagram attached to [SUPPORT-6710](https://jira.camunda.com/browse/SUPPORT-6710) in Modeler
2. Export Model to PNG (JPEG doesn't work as well)
3. Try to open a created image

__Expected Behavior__

A valid PNG is created by the Camunda Modeler.

__Environment__

 - OS:  MacOS 10.15.1, Windows 10
 - Camunda Modeler Version: 3.4.1, 3.3.4

---

Related to [SUPPORT-6710](https://jira.camunda.com/browse/SUPPORT-6710)

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #1591

### CODE REVIEW

File: client/src/app/util/__tests__/generateImageSpec.js [hunk 1]
```diff
@@ -29,6 +30,14 @@ describe('util - generateImage', function() {
       expect(image).to.exist;
     });
 
+
+    it('should automatically handle large images <' + type + '>', function() {
+
+      const image = generateImage(type, outOfBoundsSVG);
+
+      expect(image.length).to.be.greaterThan(6);
```
Comment (pinussilvestrus) [inline client/src/app/util/__tests__/generateImageSpec.js]: Just for understanding: what means 'greater than 6' here?

Comment (oguzeroglu) [reply client/src/app/util/__tests__/generateImageSpec.js]: Ah yeah, maybe I should put a comment here. Normaly if an image cannot be generated it returns a 6 character long data, something like `data=;,`, if it can be generated it returns the actualy size of the image (depending on how many bytes is it, some big number)

File: client/src/app/util/generateImage.js [hunk 2]
```diff
@@ -16,35 +16,55 @@ const ENCODINGS = [
...
-  canvg(canvas, svg);
+    dataURL = canvas.toDataURL(encoding);
+
+    if (DATA_URL_REGEX.test(dataURL)) {
+      return dataURL;
+    }
+  }
+
+  // this will generate an invalid image if we end up here
+  return dataURL;
```
Comment (pinussilvestrus) [inline client/src/app/util/generateImage.js]: Maybe, just an idea, we could raise an error here? It's something we would not expect and then, we could easily test it as well (expect error is thrown).

File: client/src/app/util/__tests__/generateImageSpec.js (hunk 1 above)
Comment (pinussilvestrus) [reply client/src/app/util/__tests__/generateImageSpec.js]: +1 for comment

File: client/src/app/util/generateImage.js (hunk 2 above)
Comment (oguzeroglu) [reply client/src/app/util/generateImage.js]: Good idea, let me talk to Volker about this, if he's ok with that we could throw an error. That would make the test easier as well

Comment (pinussilvestrus) [reply client/src/app/util/generateImage.js]: 👍

**Comment by pinussilvestrus** [comment]
`.jpg` export seems to be broken with this PR.

current `master`



`1591-png-export-scale-fix`

**Comment by oguzeroglu** [comment]
How do you export .JPG?

It works on my machine with JPEG. I have either SVG/PNG or JPEG as export options.

**Comment by oguzeroglu** [comment]
@pinussilvestrus Ah ok could generate the problem 👍

File: client/src/app/util/__tests__/generateImageSpec.js [hunk 3]
```diff
@@ -29,6 +30,14 @@ describe('util - generateImage', function() {
...
+    }).timeout(5000); // downscaling may exceed the default timeout 2000ms.
```
Comment (pinussilvestrus) [inline client/src/app/util/__tests__/generateImageSpec.js]: is the timeout a problem in the test? maybe we can wrap that into a promise inside the test case and make it async...

Comment (oguzeroglu) [reply client/src/app/util/__tests__/generateImageSpec.js]: We seem to face the same problem before:
Look at [here](https://github.com/camunda/camunda-modeler/blob/8a7a941870f653a5581f898297a324ef34c142dd/client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js#L234)

I basically applied the same solution. Creating a new canvas/writing image on it each time we downscale is a bit costly on CI machines.

Comment (oguzeroglu) [reply client/src/app/util/__tests__/generateImageSpec.js]: Is there a benefit to making this async?

Comment (pinussilvestrus) [reply client/src/app/util/__tests__/generateImageSpec.js]: I see. I just thought about making it async to ensure the timeout never is caught.

Comment (pinussilvestrus) [reply client/src/app/util/__tests__/generateImageSpec.js]: If `5000ms` is enough to ensure the test'll never fail on CI, I'd be fine with that.

**Comment by pinussilvestrus** [comment]
Besides the thing with the possible `error` throw, it looks fine for me 👍

**Comment by oguzeroglu** [comment]
@pinussilvestrus The bug occurred yesterday gave me an idea to extend our generateImage tests. I added a new case where we compare the data URLs of the generated image with the expected image, therefore if for some reason we end up messing up again we can at least catch it with tests. Please check the generateImageSpec for some feedback!

**Comment by oguzeroglu** [comment]
@nikku It turns out that it's not non-hackily possible at this point to access to log instance inside util classes. I ended up throwing an error like [here](https://github.com/camunda/camunda-modeler/blob/e391bce3aef55e1020a67601f48d3209616b4993/client/src/app/util/generateImage.js#L28) in the same class. I believe it should be fine.

**Comment by nikku** [comment]
That is exactly the way to go.

Throw an error and handle it in the appropriate place (somewhere else).

**Comment by oguzeroglu** [comment]
I reverted this PR and opened #1634 to handle logging instead of throwing an error.
