### PR TITLE
Sidepanel refactor & bugfix

### LINKED ISSUE #5729: Side panel resize action causes UI glitch
### Describe the bug

https://github.com/user-attachments/assets/c4dc2f35-ded0-49c9-bcaf-89f690037a14

### Steps to reproduce

1. Enlarge properties panel to the max
2. Drag variables beyond
3. now this happens

### Expected behavior

We stop at screen width.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: Vertical prototype
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jarekdanielak**
Closes https://github.com/camunda/camunda-modeler/issues/5729

### Proposed Changes

Add a `SidePanelContainer` component that wraps side panel children and coordinates their widths.

#### How it works

- Uses a `ResizeObserver` on the parent element to track available container width.
- Computes an effective `maxWidth` for each child panel, reserving 200px for the canvas.
- Injects `maxWidth` and a width-limiting `onLayoutChanged` wrapper into each child via `React.cloneElement`
- On layout change, runs an iterative fitting algorithm (`fitPanelsToContainer`) that progressively reduces overflowing panel widths until all panels fit within the available space.
- (!) Children declare their layout key via a `layoutPanelId` prop.

#### Other changes

- Fixed how `App#handleLayoutChanged` grabs the "current" layout before updating state.

> [!NOTE]
> All the tests in `SidePanelContainerSpec` are AI-generated.

### Try it

➡️ `npm start`

### Demo

panels-demo

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [x] Pull request __establishes context__
  * [x] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [x] __Screenshots or short videos__ showing UI/UX changes
  * [x] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

File: client/src/app/App.js [hunk 1]
```diff
@@ -940,13 +940,9 @@ export class App extends PureComponent {
...
-    const {
-      layout
-    } = this.state;
-
-    const latestLayout = merge({}, layout, newLayout);
-
-    this.setLayout(latestLayout);
+    this.setState(prevState => ({
+      layout: merge({}, prevState.layout, newLayout)
+    }));
```
Comment (philippfromme) [inline client/src/app/App.js]: What about this is _proper_? Was this broken before?

File: client/src/app/resizable-container/ResizableContainer.js [hunk 2]
```diff
@@ -210,166 +273,160 @@ export function getCSSFromProps(props) {
...
+}
+
+/**
+ * Returns the total size (width or height) of open sibling ResizableContainer elements.
+ *
+ * @param {HTMLElement} element
+ * @param {boolean} horizontal
+ * @returns {number}
+ */
+function getOpenSiblingSize(element, horizontal) {
```
Comment (philippfromme) [inline client/src/app/resizable-container/ResizableContainer.js]: I'm not sure about this. Each child imperatively queries the DOM for sibling state instead of receiving constraints from the parent. I think this is an anti-pattern. React components shouldn't need to know about their siblings. We could just lift the constraints. The parent already has all the layout state. It should compute the effective for each panel and pass it down.

File: client/src/app/App.js (hunk 1 above)
Comment (jarekdanielak) [reply client/src/app/App.js]: When we use `this.state.layout` in the `setState`, it's not guaranteed to actually be the latest state, because of how React 18 can batch state updates. When we take it from the `setState` callback, it's always up-to-date.

Comment (jarekdanielak) [reply client/src/app/App.js]: In the context of this PR, I ran into race condition when the ResizableContainer was triggering consecutive layout updates.

File: client/src/app/resizable-container/ResizableContainer.js (hunk 2 above)
Comment (jarekdanielak) [reply client/src/app/resizable-container/ResizableContainer.js]: If you mean we should have some kind of wrapper around all Resizable Containers to handle the resizing constraints, that's actually a good idea I haven't thought of... 🤔

**Comment by jarekdanielak** [comment]
Back to draft to address https://github.com/camunda/camunda-modeler/pull/5776#discussion_r2994718945

**Comment by jarekdanielak** [comment]
This is now reworked to rely on React features and our `layout` object, instead of probing the DOM directly. The top comment is updated. Ready for review. 🤞

**Comment by barmac** [comment]
I've updated the target to `main` so that we can fix the bug before the release.

File: client/src/app/side-panel/__tests__/SidePanelContainerSpec.js [hunk 3]
```diff
@@ -0,0 +1,443 @@
...
+
+    // when
+    injectedCallback({ panelA: { open: true, width: 500 } });
+
+    // then
+    expect(onLayoutChanged).to.have.been.calledOnce;
+
+    const update = onLayoutChanged.firstCall.args[0];
+
+    expect(update.panelA.width).to.be.at.most(500);
```
[the remark this answers is not in the document]
Comment (barmac) [reply client/src/app/side-panel/__tests__/SidePanelContainerSpec.js]: The suggestion looks too complicated to me, but I'd still verify if the test case works.

File: client/src/app/side-panel/SidePanelContainer.js [hunk 4]
```diff
@@ -0,0 +1,175 @@
...
+    }
+  }, [ containerWidth, layout ]);
+
+  return (
+    <div ref={ containerRef } style={ { display: 'contents' } }>
+      { panels.map((child) => {
+        const panelId = child.props.layoutPanelId;
+        const maxWidth = getMaxWidth(panelId);
+
+        return React.cloneElement(child, {
```
Comment (philippfromme) [inline client/src/app/side-panel/SidePanelContainer.js]: The React docs explicitly recommend not using `cloneElement`.

Image

It silently overrides props and makes the data flow hard to trace. The docs also list alternatives: https://react.dev/reference/react/cloneElement#alternatives

**Comment by philippfromme** [comment]
The width of the properties panel between editors is not consistent. I don't know what exactly is happening. Sometimes it's also jumping to a different width after the initial render.

electron_9FoWLJdCCH

My assumption is that the properties panel is consistent between editors that support resizing, whether or not they have an additional variables panel or not.

**Comment by philippfromme** [comment]
@jarekdanielak What is the state of this? Do we still want to get this into the release?

**Comment by jarekdanielak** [comment]
@philippfromme pushed an update. If it goes to the release, it goes, but I don't see it as critical.

Update:
- Instead of `React.cloneElement`, the new version uses internal React context in the `SidePanelContainer` to coordinate the resizing.
- To keep the component that implement the panels as they are (`SidePanel` and `VariablesSidePanel`), the children of the `SidePanelContainer` are wrapped in `SidePanelSlot` to handle passing the props.

Have a look at the updated "How it works" section in the top comment.

File: client/src/app/App.js (hunk 1 above)
Comment (Buckwich) [reply client/src/app/App.js]: for reference: https://github.com/reactwg/react-18/discussions/21

its recommended to use callbacks to get previous state 
```
setState((prevState)=> ({...prevState, field: 'newValue' }))
```

cf. https://camunda.slack.com/archives/GP70M0J6M/p1775053908068889?thread_ts=1774258422.435789&cid=GP70M0J6M

**Comment by philippfromme** [comment]
I tried simplifying it removing the need for yet another container (`SidePanelSlot`) but even with that the jumping issue remains. I don't think it's realistic for this to make it into the release. As it's Desktop Modeler only the delay will only be a month anyway.

**Comment by jarekdanielak** [comment]
There were two problems:
- "fitting to space" login in the `SidePanelContainer` essentially ran twice for every render,
- the max width of a "standalone" panel was calculated differently, than for panels inside the container.

I cleaned it up and ensured all panels new follow the "available space - `MIN_CANVAS_WIDTH`" rule.

Give it a try:

panels-demo-bugfix

File: client/src/app/side-panel/SidePanelContainer.js [hunk 5]
```diff
@@ -0,0 +1,136 @@
...
+  const containerWidth = useParentWidth(containerRef);
+
+  const panelIds = useMemo(() => {
+    return React.Children.toArray(children)
+      .map(child => child.props.panelId);
+  }, [ children ]);
+
+  const getMaxWidth = (panelId) => {
+    const siblingsWidth = getSiblingsWidth(panelId, panelIds, layout);
+    return containerWidth - siblingsWidth - MIN_CANVAS_WIDTH;
```
[the remark this answers is not in the document]
Comment (jarekdanielak) [reply client/src/app/side-panel/SidePanelContainer.js]: https://github.com/camunda/camunda-modeler/pull/5776/changes/7215fd83483cdb1623f3fd2ec3817035a7204dfb

File: client/src/app/side-panel/SidePanel.js [hunk 6]
```diff
@@ -62,9 +64,14 @@ export default function SidePanel(props) {
   const {
     children,
     layout,
+    maxWidth,
     onLayoutChanged
   } = props;
 
+  const containerRef = useRef();
+  const parentWidth = useParentWidth(containerRef);
+  const effectiveMaxWidth = maxWidth || (parentWidth - MIN_CANVAS_WIDTH);
```
[the remark this answers is not in the document]
Comment (jarekdanielak) [reply client/src/app/side-panel/SidePanel.js]: https://github.com/camunda/camunda-modeler/pull/5776/changes/7215fd83483cdb1623f3fd2ec3817035a7204dfb

**Comment by jarekdanielak** [comment]
Fixed one problem pointed by Copilot's review.

We agreed with @philippfromme that this is going to be verified & merged after the release on 14 April.

**Comment by barmac** [comment]
Agreed, the reported problem is an edge case. I don't expect the users to fall into that.

**Comment by jarekdanielak** [comment]
@philippfromme let's get this merged.

File: client/src/app/side-panel/SidePanelGroup.js [hunk 7]
```diff
@@ -0,0 +1,137 @@
...
+import React, {
+  createContext,
+  useContext,
+  useMemo,
+  useRef
+} from 'react';
+
+import useParentWidth from './useParentWidth';
+
+export const MIN_CANVAS_WIDTH = 200;
```
Comment (philippfromme) [inline client/src/app/side-panel/SidePanelGroup.js:20]: With canvas logic leaking into it this is not a truly generic component for now. But we can fix that once we need to reuse it.

**Review by philippfromme — APPROVED** [review]
Works as expected! 👍🏻
