### PR TITLE
fix(client): only apply default templates to unsaved diagram

### LINKED ISSUE #1373: Default Element Templates Always Applied
foobar

__Describe the Bug__

When opening a diagram that contains a `camunda:property` set using an element template the property value is not shown in the properties panel.

__Steps to Reproduce__

1. Use the following element template:

```javascript
[
  {
     "name":"Test",
     "id":"test",
     "isDefault":true,
     "appliesTo":[
        "bpmn:Process"
     ],
     "properties":[
        {
           "label":"Test",
           "description":"This is a test.",
           "type":"String",
           "binding":{
              "type":"camunda:property",
              "name":"Test Property"
           },
           "constraints":{
              "notEmpty":true
           }
        }
     ]
  }
]
```

2. Open this diagram:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:camunda="http://camunda.org/schema/1.0/bpmn" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.1.0">
  <bpmn:process id="Process_1" isExecutable="false" camunda:modelerTemplate="test">
    <bpmn:extensionElements>
      <camunda:properties>
        <camunda:property name="Test Property" value="foobar" />
      </camunda:properties>
    </bpmn:extensionElements>
  </bpmn:process>
  <bpmndi:BPMNDiagram id="BPMNDiagram_1">
    <bpmndi:BPMNPlane id="BPMNPlane_1" bpmnElement="Process_1" />
  </bpmndi:BPMNDiagram>
</bpmn:definitions>
```

__Expected Behavior__

Property is shown.

__Environment__

 - OS: Windows 10
 - Camunda Modeler Version: 3.1.0

### PR DESCRIPTION
**Pull request by philippfromme**
Closes #1373

### CODE REVIEW

File: client/src/app/tabs/bpmn/BpmnEditor.js [hunk 1]
```diff
@@ -301,20 +303,31 @@ export class BpmnEditor extends CachedComponent {
 
   handleImport = (error, warnings) => {
     const {
+      isNew,
       onImport,
       xml
     } = this.props;
 
+    let {
```
Comment (barmac) [inline client/src/app/tabs/bpmn/BpmnEditor.js]:
```suggestion
    const {
```
It's not modified anywhere.

File: client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js [hunk 2]
```diff
@@ -1064,6 +1067,103 @@ describe('<BpmnEditor>', function() {
...
+      cache.add('editor', {
+        cached: {
+          modeler
+        }
+      });
+
+      function onImport() {
+
+        // then
+        expect(invokeSpy).to.have.been.calledWith(applyDefaultTemplates);
```
Comment (barmac) [inline client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js]:
```suggestion
        try {
          expect(invokeSpy).to.have.been.calledWith(applyDefaultTemplates);
        } catch (error) {
          return done(error);
        }
```
This will allow to avoid `timeout`ed tests in case feature is broken.

File: client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js [hunk 3]
```diff
@@ -1284,13 +1384,15 @@ async function renderEditor(xml, options = {}) {
...
-    getPlugins
+    getPlugins,
+    isNew
   } = options;
 
   const wrapper = await mount(
     <TestEditor
       id={ id || 'editor' }
       xml={ xml }
+      isNew={ isNew === false ? false : true }
```
Comment (barmac) [inline client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js]:
```suggestion
      isNew={ isNew !== false }

File: client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js (hunk 2 above)
Comment (philippfromme) [reply client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js]: Makes sense 👍

File: client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js (hunk 3 above)
Comment (philippfromme) [reply client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js]: 🤣
