### PR TITLE
fix: update menu when element templates modal is open

### LINKED ISSUE #3483: Shortcuts override the search input in template selection modal
### Describe the bug

If you open the template selector popup window the search input field has the focus, and if you press the button "p", everything works as expected. But if you press any button which is a shortcut, for example "n", or "a", it does not search but execute the command bound to that shortcut. The biggest problem is the backspace. Press p, and then backspace. It will remove the Task element, but won't close the Template selector popup window. If you select the template after this, it will throw an error saying : `Cannot read properties of undefined (reading 'children')`

image

### Steps to reproduce

1. Open editor
2. Create a new Task
3. Click on template selection button
4. Press "p" to start filtering the templates 
5. Press backspace to delete the letter "p"
6. It will remove the Task

OR

1. Open editor
2. Create a new Task
3. Click on template selection button
4. Press "n" to start filtering the templates 
5. It won't filter the templates as expected but it will open the Create element context menu

### Expected behavior

When the search input field has the focus, we should disable shortcuts.

### Environment

- OS:  Windows 11
- Camunda Modeler Version: 5.9.0-nightly.20230227
- Execution Platform: Camunda Platform
- Installed plug-ins: none

### Additional context

Related to [SUPPORT-21053](https://jira.camunda.com/browse/SUPPORT-21053)

### PR DESCRIPTION
**Pull request by barmac**
Closes #3483

[SUPPORT-21053](https://jira.camunda.com/browse/SUPPORT-21053)

### CODE REVIEW

**Comment by barmac** [comment]
@nikku @philippfromme anything preventing us from merging this?

File: client/src/app/tabs/bpmn/BpmnEditor.js [hunk 1]
```diff
@@ -230,7 +230,8 @@ export class BpmnEditor extends CachedComponent {
       'searchPad.closed',
       'searchPad.opened',
       'popupMenu.opened',
-      'popupMenu.closed'
+      'popupMenu.closed',
+      'elementTemplates.select'
```
Comment (nikku) [inline client/src/app/tabs/bpmn/BpmnEditor.js:234]: What feels a little bit magically to me is that we don't react on modal closing to update the menu. 

This is a theoretic case as we seem to have enough update checks in place to re-trigger menu update after close (refreshing available actions).

**Review by nikku — APPROVED** [review]
