### PR TITLE
Complete Editing on Save

### LINKED ISSUE #1473: Labels don't get saved when editor is still focused on the text
__Describe the Bug__

When direct editing is active, the currently edited text is not being flushed on diagram save:

Aug-20-2019 17-06-17

__Steps to Reproduce__

- enter the edit mode of any label (focus)
- save the diagram without deactivating the focus
- open the saved diagram

result: the label was not saved

__Expected Behavior__

* [ ] before actually saving the file complete direct editing so that the content of the label is synced into the XML

__Environment__

Camunda Modeler: v3.2.3
Operating System: OSX

### PR DESCRIPTION
**Pull request by oguzeroglu**
Closes #1473 

* ensure changes made through direct editing are being saved when tab is saved

### CODE REVIEW

File: client/src/app/App.js [hunk 1]
```diff
@@ -1300,6 +1300,8 @@ export class App extends PureComponent {
 
   async saveTab(tab, options) {
 
+    this.triggerAction('saveEditing');
```
Comment (pinussilvestrus) [inline client/src/app/App.js]: If we decide to go this direction, we will have to make sure, all kind of Editors support this. E.g. it would currently throw an error inside a DMN file:

```js
saveEditing is not a registered action
    at error (webpack-internal:///./node_modules/dmn-js-drd/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:260:10)
    at DrdEditorActions.EditorActions.trigger (webpack-internal:///./node_modules/dmn-js-drd/node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:170:11)
    at DmnEditor._defineProperty (webpack-internal:///./src/app/tabs/dmn/DmnEditor.js:344:54)
    at MultiSheetTab._defineProperty (webpack-internal:///./src/app/tabs/MultiSheetTab.js:139:21)
    at EditorTab.triggerAction (webpack-internal:///./src/app/tabs/EditorTab.js:36:34)
    at App.failSafe (webpack-internal:///./src/app/App.js:657:18)
    at App.eval (webpack-internal:///./src/app/App.js:1856:20)
    at App.saveTab (webpack-internal:///./src/app/App.js:1390:10)
    at App.failSafe (webpack-internal:///./src/app/App.js:564:21)
    at App.eval (webpack-internal:///./src/app/App.js:1856:20) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]
```

Comment (oguzeroglu) [reply client/src/app/App.js]: I closed the bpmn-js PR and implemented this as a module under the Camunda modeler within this PR, so this is fixed. Thanks for the catch!

File: client/src/app/tabs/bpmn/modeler/features/save-editing/SaveEditing.js [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+ * distributed with this work for additional information regarding copyright
+ * ownership.
+ *
+ * Camunda licenses this file to you under the MIT; you may not use this file
+ * except in compliance with the MIT License.
+ */
+
+export default function SaveEditing(editorActions, injector) {
+  editorActions.register('saveEditing', function() {
+    var directEditing = injector.get('directEditing', false);
```
Comment (pinussilvestrus) [inline client/src/app/tabs/bpmn/modeler/features/save-editing/SaveEditing.js]: Can't we assume, that `directEditing` is available in all Editors which will use this module? Therefore we could inject it directly without the additional `injector` dependency.

Comment (oguzeroglu) [reply client/src/app/tabs/bpmn/modeler/features/save-editing/SaveEditing.js]: The directEditing dependency is not available for DMN Table so we need to check if it exists here. If we don't register this action for DMN Tables, then we get the NotRegistered exception. So it needs to be registered but do nothing.

Comment (oguzeroglu) [reply client/src/app/tabs/bpmn/modeler/features/save-editing/SaveEditing.js]: The other solution would be to implement another class only for DMN Tables which registers saveEditing to noop function, but I find the current solution better.

**Comment by oguzeroglu** [comment]
@pinussilvestrus @philippfromme Do you think there's a way to properly test this within camunda-modeler? There seems to be no tests for HandToolOnSpace inside camunda-modeler as well so I'm not sure how to test the functionality of editorActions in this project.

**Comment by philippfromme** [comment]
AFAIK we don't test modeler features at all. We could easily change that.

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus @philippfromme Do you think there's a way to properly test this within camunda-modeler? There seems to be no tests for HandToolOnSpace inside camunda-modeler as well so I'm not sure how to test the functionality of editorActions in this project.

It should be possible to write a test like [this one](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/__tests__/PropertiesPanelKeyboardBindingsSpec.js#L34). You can then use the editorActions via: 

```js
const editorActions = modeler.get('editorActions');
editorActions.trigger(...)
```

You could then listen for the [`directEditing.complete`](https://github.com/bpmn-io/diagram-js-direct-editing/blob/master/lib/DirectEditing.js#L111) event

```js
const spy = sinon.spy();
const eventBus = modeler.get('eventBus');
eventBus.on('directEditing.complete', spy);

expect(spy).to.have.been.called
```

**Comment by oguzeroglu** [comment]
@pinussilvestrus Ended up writing a mock for editorActions and injector. The PR is ready now.

File: resources/diagram/simple.bpmn [hunk 3]
```diff
@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn">
+<bpmn:definitions xmlns:bpmn="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:di="http://www.omg.org/spec/DD/20100524/DI" xmlns:dc="http://www.omg.org/spec/DD/20100524/DC" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="Definitions_1" targetNamespace="http://bpmn.io/schema/bpmn" exporter="Camunda Modeler" exporterVersion="3.4.0-dev">
```
Comment (philippfromme) [inline resources/diagram/simple.bpmn]: Why changing this diagram?

Comment (oguzeroglu) [reply resources/diagram/simple.bpmn]: Yes, this actually looks like a stupid mistake 🥇 . Did another commit now that removes this change.

Comment (philippfromme) [reply resources/diagram/simple.bpmn]: A ~~stupid~~ mistake. 👍
