### PR TITLE
fix(task-testing): do not truncate process var values

### LINKED ISSUE #5723: Variables might be truncated
### Describe the Bug

When fetching the variables after a test we aren't explicit about the fact that we don't want truncated variables. By default variables are truncated (cf. https://docs.camunda.io/docs/apis-tools/orchestration-cluster-api-rest/specifications/search-variables/).

### Steps to Reproduce

1. Test task that produces large variables
2. Variables are truncated

### Expected Behavior

No truncated variables.

### Environment

- Library version: latest

### PR DESCRIPTION
**Pull request by ev-codes**
### Proposed Changes

closes #5723 

Show the full process variable value in task testing output.

[See issue description](https://github.com/camunda/camunda-modeler/issues/5723) for how you can test this change.

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [x] Pull request __establishes context__
  * [x] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [ ] __Screenshots or short videos__ showing UI/UX changes
  * [x] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

File: app/lib/zeebe-api/zeebe-api.js [hunk 1]
```diff
@@ -417,14 +417,15 @@ class ZeebeAPI {
   /**
    * Search variables. Requires Camunda REST client.
    *
-   * @param {{ endpoint: import("./endpoints").Endpoint, processInstanceKey: string }} config
+   * @param {{ endpoint: import("./endpoints").Endpoint, processInstanceKey: string, truncateValues?: boolean }} config
```
Comment (nikku) [inline app/lib/zeebe-api/zeebe-api.js]: What is the use-case to not truncate a value? I believe we rely on results to be valid JSON.

File: client/src/app/tabs/cloud-bpmn/side-panel/tabs/task-testing/__tests__/TaskTestingApiSpec.js [hunk 2]
```diff
@@ -212,4 +212,38 @@ describe('<TaskTestingApi>', function() {
...
+          path: 'path/to/file.bpmn'
+        },
+        null
+      );
+
+      // when
+      await api.getProcessInstanceVariables('test-process-instance-key');
+
+      // then
+      expect(searchVariablesSpy).to.have.been.calledOnce;
```
Comment (nikku) [inline client/src/app/tabs/cloud-bpmn/side-panel/tabs/task-testing/__tests__/TaskTestingApiSpec.js]: I'd like to not add such test, [instead fix the default behavior if possible](https://github.com/camunda/camunda-modeler/pull/5788/changes#r2988004296).

File: app/lib/zeebe-api/zeebe-api.js (hunk 1 above)
Comment (ev-codes) [reply app/lib/zeebe-api/zeebe-api.js]: The use case to not truncate (i.e., to request the whole variable) is so that the user can see the entire response (like an entire JSON object).

There is not a clear use case to truncate (i.e., to request only the first characters of the variable). I thought there were other usages of the `searchVariables` function elsewhere in this application. But reading through the codebase again, it looks like only task testing is using it.

So I'll remove the `truncateValues` parameter and always pass `truncateValues = false` in the orchestration cluster API call.

File: client/src/app/tabs/cloud-bpmn/side-panel/tabs/task-testing/__tests__/TaskTestingApiSpec.js (hunk 2 above)
Comment (ev-codes) [reply client/src/app/tabs/cloud-bpmn/side-panel/tabs/task-testing/__tests__/TaskTestingApiSpec.js]: I agree, [see my response here](https://github.com/camunda/camunda-modeler/pull/5788/changes#r2988065619) 🙂

File: app/lib/zeebe-api/zeebe-api.js (hunk 1 above)
Comment (barmac) [reply app/lib/zeebe-api/zeebe-api.js]: 100% agreed we don't need to expose a way to truncate values if we never want to do that
