### PR TITLE
Fix user journey statistics for C8 deploy and start instance

### LINKED ISSUE #5076: Camunda 8 Deployment and Start Instance Tracking Broken
### Describe the bug

Tracking of Camunda 8 Deployment and Start Instance was accidentally broken in the context of https://github.com/camunda/camunda-modeler/pull/4926 and needs to be reintroduced.

Context: https://github.com/camunda/camunda-modeler/pull/4926#discussion_r2128683940

### Steps to reproduce

1. Deploy or start instance of Camunda 8 BPMN
2. Check Mixpanel
3. No events

### Expected behavior

Tracking works.

### Environment

- Camunda Modeler Version: 5.36

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philippfromme**
Adds user journey statistics for C8 deploy and start instance which was accidentally removed during a refactoring.

Closes #5076

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

**Comment by barmac** [comment]
We want to merge this to `main` to avoid a regression.

**Comment by barmac** [comment]
I tried this out and unfortunately there is an uncaught error when deploying process app with RPA file to 8.6
image
This should be tracked as a deployment error.

image

**Comment by barmac** [comment]
This is actually a common thing for all deployment errors. `error` is not provided

**Comment by barmac** [comment]
There is however `deployment` property which looks like the error:
image

File: client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js [hunk 1]
```diff
@@ -123,6 +125,27 @@ export default function DeploymentPluginOverlay(props) {
     };
   }, [ connectionChecker, deployment, setConfig, setConnectionCheckResult ]);
 
+  useEffect(() => {
+    const onDeployed = ({ deploymentResult, endpoint, gatewayVersion }) => {
+      triggerAction('emit-event', {
+        type: deploymentResult.success ? 'deployment.done' : 'deployment.error',
+        payload: {
+          deployment: deploymentResult.response,
```
Comment (barmac) [inline client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js]: This is where the error is passed.

Comment (barmac) [reply client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js]: See old version of the code: https://github.com/camunda/camunda-modeler/blob/v5.35.0/client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js#L572

**Comment by philippfromme** [comment]
@barmac I missed this part:

```
error: {
  ...response,
  code: getGRPCErrorCode(response)
},
```

Link: https://github.com/camunda/camunda-modeler/pull/4926/commits/9601855763dc6eea5cceabb9b3c98914fb87d734#diff-5f32eb059df8b990c64b69db90c7e7fa2c0b34755673837a05b8491c8cdb1475L576

I'll add that.

**Comment by philippfromme** [comment]
@barmac It's fixed now. I realize I removed the entire GRPC error code logic. 🤦🏻

**Comment by barmac** [comment]
This works correctly now.
