### PR TITLE
fix: ignore files without metadata

### LINKED ISSUE #4917: Process applications resources crashes when encountering file with no metadata
### Describe the bug

When encountering a file with no metadata (e.g. broken BPMN file) the process applications resource provider crashes since it doesn't account for this case.

Image

Image

### Steps to reproduce

1. Have a broken BPMN file in your process application
2. Open any file in the process application
3. Modeler crashes

### Expected behavior

Files without metadata should be ignored.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

This makes sure that a file without metadata (case of broken files) can still be handled correctly by the resources provider. We ignore such files instead of crashing the application.

https://github.com/user-attachments/assets/97be214c-036f-43c7-9ed5-a1819330d8a8

Closes #4917

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [x] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: client/src/plugins/process-applications/__tests__/ResourcesProviderSpec.js [hunk 1]
```diff
@@ -251,6 +264,22 @@ describe('ResourcesProvider', function() {
...
+    const processApplications = createProcessApplications(NO_METADATA);
+
+    const resourcesProvider = new ResourcesProvider(resourceLoader, processApplications);
+
+    // when
+    const resources = resourcesProvider.getResources();
+
+    // then
+    expect(resources).to.eql([]);
+  });
```
Comment (philippfromme) [inline client/src/plugins/process-applications/__tests__/ResourcesProviderSpec.js:282]:
```suggestion
  });

```

**Review by philippfromme — APPROVED** [review]
💪🏻
