### PR TITLE
Prevent error when displaying overlay

### LINKED ISSUE #5333: Overlay crash when task testing is activated repeatedly
### Describe the bug

Overlay crash:

https://github.com/user-attachments/assets/b9b6e4f8-659d-45c2-9b35-e0ac5420b0e7

### Steps to reproduce

1. Start task testing
2. Switch tabs, click multiple times
3. now this happens

### Expected behavior

No crashes.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by barmac**
### Proposed Changes

Two changes:

1. Log error instead of failing to render overlay without anchor
2. Make sure that deployment overlay is rendered only with anchor present

Closes #5333

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [ ] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js [hunk 1]
```diff
@@ -118,7 +118,7 @@ export default function DeploymentPlugin(props) {
         </button>
       </Fill>
     ) }
-    { overlayOpen && (
+    { overlayOpen && anchorRef.current && (
```
Comment (philippfromme) [inline client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js:121]: Is this still necessary? If so then we should add it to all features using overlays. Otherwise we can just rely on the overlay to handle this case. 🤔

Comment (barmac) [reply client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js:121]: I reworked the PR to explicitly throw. Yes, we can use this condition in all places where we create overlay.

Comment (barmac) [reply client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js:121]: To your question: Yes, it's necessary.

Comment (philippfromme) [reply client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js:121]: If we throw, then yes, it's necessary. 👍🏻
