### PR TITLE
fix: access DI through utility

### LINKED ISSUE #5764: Properties panel header missing from subprocess
### Describe the bug

In the new layout, the header is not shown when a subprocess is selected:

Image

### Steps to reproduce

1. Select a subproces.
2. No header.

### Expected behavior

Show the header.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philippfromme**
### Proposed Changes

image

Closes #5764

### Checklist

Ensure you provide everything we need to review your contribution:

* [ ] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [ ] Pull request __establishes context__
  * [ ] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [ ] __Brief textual description__ of the changes
  * [ ] __Screenshots or short videos__ showing UI/UX changes
  * [ ] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

File: client/src/app/tabs/cloud-bpmn/side-panel/SidePanelHeader.js [hunk 1]
```diff
@@ -163,15 +171,13 @@ export const PanelHeaderProvider = (injector) => {
...
+        return null;
+      }
 
-      let config;
-      try {
-        config = injector.get('config.elementTemplateIconRenderer', false);
-      } catch (e) {
+      const concreteType = getConcreteType(element);
 
-        // service may not be available
```
Comment (nikku) [inline client/src/app/tabs/cloud-bpmn/side-panel/SidePanelHeader.js:173]: 🙃

**Comment by barmac** [comment]
Works great.
