### PR TITLE
Handle template errors as warnings

### LINKED ISSUE #2287: Don't report element template validation "errors" to sentry
__Describe the Bug__

Currently element template validation errors (e.g., `template(id: <abc>, name: <abc>): missing binding for property "0"` are logged and treated as errors. Hence they are also logged to sentry. See for example: 
[ex1](https://sentry.io/organizations/camunda-modeling/issues/2386508793/?project=5223041&query=is%3Aunresolved+template&statsPeriod=14d)
[ex2](https://sentry.io/organizations/camunda-modeling/issues/2336443227/?project=5223041&query=is%3Aunresolved+template&statsPeriod=14d)

__Steps to Reproduce__

1. Have usage statistics enabled
2. Set up an element template with an invalid property binding
3. See how an error is logged in the Camunda Modeler
4. See how the error appears in sentry

__Expected Behavior__

These validation *"errors"* should not be logged to sentry. 

__Environment__

- Camunda Modeler Version: 4.7 | 4.8
- Execution Platform: Camunda Platform
- Installed plug-ins: none

### PR DESCRIPTION
**Pull request by pinussilvestrus**
Closes #2287

This PR handles element [template validation errors](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/ElementTemplatesLoader.js#L82) as warnings - and avoids showing the stacktrace for these since it will be the same for each validation warning (no real benefit). I also think it's okay to assume these errors are only validation errors since we handle [template loading errors](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/BpmnEditor.js#L142) separately. 

This also prevents sending the validation errors to Sentry.

**before**
Bildschirmfoto 2021-06-10 um 09 40 15

**after**
Bildschirmfoto 2021-06-10 um 09 49 33

### CODE REVIEW

File: client/src/plugins/error-tracking/ErrorTracking.js [hunk 1]
```diff
@@ -112,6 +112,11 @@ export default class ErrorTracking extends PureComponent {
           return;
         }
 
+        // avoid sending element templates errors
+        if (isTemplateError(error)) {
```
Comment (nikku) [inline client/src/plugins/error-tracking/ErrorTracking.js:116]: Where are these errors thrown? From the architecture perspective I'd rather make sure the errors do not bubble up as _errors_ but as _warnings_ (and thus do not get captured).

Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/ErrorTracking.js:116]: The errors got thrown inside the properties panel Validator (cf. https://github.com/camunda/camunda-modeler/issues/2287#issuecomment-856764433). Handling them as warnings inside the Camunda Modeler might be a thing we should consider.

Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/ErrorTracking.js:116]: I can barely remember @MaxTru was considering this as part of the last spring cleaning. Not sure what we come up with though.

Comment (nikku) [reply client/src/plugins/error-tracking/ErrorTracking.js:116]: It just feels like a flaw to mix the element template concern into our core sentry error handling logic. An alternative could be to explicitly flag errors as warnings and ignore these (not send them to sentry). Either way we should not add template detection into that place :wink:

Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/ErrorTracking.js:116]: We can probably add this concern to the BpmnEditor. I will find out, thanks for the recommendation 👍

**Review by MaxTru — APPROVED** [review]

**Comment by pinussilvestrus** [comment]
I agreed with @andreasgeier that no extra design review is necessary for this one.
So, let's merge it and verify that Sentry is cleaner after the next release.
