### PR TITLE
fix(tabs): don't mark dirty after save

### LINKED ISSUE #2654: Weird behaviour with unsaved tabs
__Describe the Bug__

Saved tabs appear as unsaved when opening and closing new diagrams.

__Steps to Reproduce__

https://user-images.githubusercontent.com/25825387/147941202-001efccc-c106-4dd3-9729-adba04ed84af.mov

1. open a new diagram
2. make a change and save file
3. open a new diagram and close it
4. see that first tab saved appears as unsaved

__Expected Behavior__

The tab saved shouldn't be displayed as unsaved - shouldn't display blue marker

__Environment__

- OS: MacOS 11.6
- Camunda Modeler Version: latest on develop

### PR DESCRIPTION
**Pull request by marstamm**
closes #2654

Tests were already present for this behavior, but because we mocked bpmn-js it was not caught:
https://github.com/camunda/camunda-modeler/blob/ff14d9615b8fb78ea1e41b17a24cf7a330f24840/client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js#L1212-L1227

I adjusted the modeler mock accordingly

### CODE REVIEW

**Comment by philippfromme** [comment]
No tests? 🤡 Or would they fails without the adjusted mock?

**Comment by marstamm** [comment]
We already have Tests for this (e.g. the one linked in the description) and they would fail with the adjusted mock before.

File: client/src/app/tabs/dmn/DmnEditor.js [hunk 1]
```diff
@@ -749,6 +747,8 @@ export class DmnEditor extends CachedComponent {
       error = _error;
     }
 
+    const stackIdx = modeler.getStackIdx();
```
Comment (philippfromme) [inline client/src/app/tabs/dmn/DmnEditor.js:750]: We always save the stack index even in the case of an error. We don't do that for BPMN. 🤔

Comment (marstamm) [reply client/src/app/tabs/dmn/DmnEditor.js:750]: I noticed that as well, but decided to not touch it for now. Because it was this way before, I would consider it out of scope for this ticket.
Of course, we should investigate if this is causes a problem and create a follow-up for it.

Comment (philippfromme) [reply client/src/app/tabs/dmn/DmnEditor.js:750]: Okay, then let's have a follow-up issue for it. The code is being changed without any test verifying what the change does.

Comment (marstamm) [reply client/src/app/tabs/dmn/DmnEditor.js:750]: You're right, I forgot to change the dmn-js mock. I'll fix that

Comment (philippfromme) [reply client/src/app/tabs/dmn/DmnEditor.js:750]: 👍🏻

Comment (marstamm) [reply client/src/app/tabs/dmn/DmnEditor.js]: I aligned the DMN save with BPMN in 756dfb5be2f32b9df481130416cf3806d38060c2

**Review by philippfromme — APPROVED** [review]
I fixed a broken test (cf. https://github.com/camunda/camunda-modeler/pull/2694/commits/54005bc603fc8a541f7824fcd2a51ac4f2831616) and added the test verifying the editor is dirty after an export error to the BPMN editor tests as well (cf. https://github.com/camunda/camunda-modeler/pull/2694/commits/24796bf61b95c13c5354171bdc784f4f85f0bb0c).

Good job! 🧑‍🏭

**Comment by marstamm** [comment]
:tada: 

Thank you for helping out with this one!
