### PR TITLE
fix: attach DMN overview only after parent rendered

### LINKED ISSUE #5880: DMN (Cannot read properties of null (reading 'get'))
### Describe the bug

There is no problem on Camunda Modeler 5.44.0. Starting from 5.45.0, I am observing an issue.

Cannot read properties of null (reading 'get')
    at get (webpack://camundanode_modules/dmn-js-shared/lib/base/Manager.js:335:19)
    at attachTo (webpack://camunda-modeler-client/src/app/tabs/dmn/modeler/DmnModeler.js:318:19)
    at attachOverviewTo (webpack://camunda-modeler-client/src/app/tabs/dmn/DmnEditor.js:363:14)
    at file:///C:/myfiles/distrib/camunda-modeler-5.46.1-win-x64/resources/app.asar/public/bundle.js:179:7113727
    at listener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:457:33)
    at _invokeListener (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:431:23)
    at _invokeListeners (webpack://camundanode_modules/diagram-js/lib/core/EventBus.js:379:23)
    at fire (webpack://camundanode_modules/dmn-js-shared/lib/base/Manager.js:570:26)
    at _emit (webpack://camundanode_modules/dmn-js-shared/lib/base/Manager.js:391:9)
    at apply (webpack://camundanode_modules/min-dash/dist/index.js:588:7) [ error ]

### Steps to reproduce

1. Create DMN file Camunda 7.23. Save file. Close Camunda Modeler
2. Open Camunda Modeler. Open Decision Table
3. now this happens
Image
Image

### Expected behavior

The error does not occur

### Environment

- OS: [Windows 11]
- Camunda Modeler Version: [5.46.1]
- Execution Platform: [Camunda 7.23]
- Installed plug-ins: [-]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philippfromme**
**Problem:** Opening a DMN file and switching to a non-DRD view (e.g., decision table) crashed because the overview was attached before its parent DOM node existed.

**Root cause:** The`views.changed` event fires synchronously during `modeler.open(view)`, before React re-renders the overview container. Attaching the overview to a not-yet-rendered ref caused the crash.

**Changes:**

- Moved overview attach/detach from `views.changed` to `componentDidUpdate`

- Consolidated overview state management into `modeler.updateOverview`

- Guarded `drgElementOpened` in `views.changed` handler against missing parent node

- Moved `overviewOpen` emit into the modeler

electron_XhCVJ93ASz

Closes #5880

### Checklist

Ensure you provide everything we need to review your contribution:

* [x] Contribution __meets our [definition of done](https://github.com/bpmn-io/.github/blob/main/resources/DEFINITION_OF_DONE.md)__
* [x] Pull request __establishes context__
  * [x] __Link to related issue(s)__, i.e. `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`
  * [x] __Brief textual description__ of the changes
  * [x] __Screenshots or short videos__ showing UI/UX changes
  * [ ] __Steps to try out__, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)

### CODE REVIEW

File: client/src/app/tabs/cloud-dmn/DmnEditor.js [hunk 1]
```diff
@@ -194,13 +188,32 @@ export class DmnEditor extends CachedComponent {
...
+
+    if (shouldAttach && !this._overviewAttached) {
+      modeler.attachOverviewTo(this.overviewRef.current);
+      this._overviewAttached = true;
+
+      if (isOverviewOpen(this.props)) {
+        modeler._emit('overviewOpen');
+      }
+    } else if (!shouldAttach && this._overviewAttached) {
+      modeler.detachOverview();
```
Comment (nikku) [inline client/src/app/tabs/cloud-dmn/DmnEditor.js]: `_overviewAttached` should be state tracked by modeler?

Comment (nikku) [reply client/src/app/tabs/cloud-dmn/DmnEditor.js]: We seem to consult two sources of truth here - the DOM `this.overviewRef.current` to determine if the overview is open and props `isOverviewOpen(this.props)`.

Can we have a single source of truth instead? And can't we move the whole state management to `modeler` - so this becomes

```
  const modeler = this.getModeler();
  const overviewRef = this.overviewRef.current;
  const open = isOverviewOpen(this.props)

  modeler.updateOverview(overviewRef, open);
```

File: client/src/app/tabs/cloud-dmn/DmnEditor.js [hunk 2]
```diff
@@ -201,6 +189,12 @@ export class DmnEditor extends CachedComponent {
     }
   }
 
+  _updateOverview() {
```
Comment (nikku) [inline client/src/app/tabs/cloud-dmn/DmnEditor.js:192]: So simple, so clean ✨

File: client/src/app/tabs/cloud-dmn/DmnEditor.js (hunk 1 above)
Comment (philippfromme) [reply client/src/app/tabs/cloud-dmn/DmnEditor.js]: 👍🏻

**Review by nikku — APPROVED** [review]
Works like a charm. Thanks for the follow-ups
