### PR TITLE
Move to origin save

### LINKED ISSUE #982: Negative Coordinates forbidden in Diagram Interchange
__Describe the Bug__

The Camunda Modeler allows negative coordinates in BPMN, CMMN and DMN diagram interchange. 

All three specifications explicitly require positive coordinates only (see quotes at the and of the report). This breaks model interchange with several BPMN tools and is reported as a broken model by others. 

In addition, this behaviour frequently causes usability problems for Camunda users with models being either hidden completely or only partially visible when opened in Camunda Modeler even though enough screen space would be available.

This has been uncovered during dry-runs for the next demo of the BPMN Model Interchange Working Group at the OMG.

__Steps to Reproduce__

1. Create a new BPMN, CMMN or DMN diagram
2. Move an element to the left or on top of the 0,0 point indicated by the grey cross in the upper left corner.

__Expected Behavior__

When BPMN XML is exported, all DI coordinates are positive.

__Environment__

 - OS: Linux
 - Camunda Modeler Version: 2.1.0-nightly of today

__Specification Quotes__

BPMN 2.0.2 page 371 (PDF 401):
> BPMNPlane element is always owned by a BPMNDiagram and represents the root diagram element of that diagram. The plane represents a 2 dimensional surface with an origin at (0, 0) along the x and y axes with increasing coordinates to the right and bottom. Only positive coordinates are allowed for diagram elements that are nested in a BPMNPlane. This means that the union of all the nested elements’ bounds is deemed to be located at the plane’s origin point.

BPMN 2.0.2 page 372 (PDF 402):
> The bounds of a BPMNShape are always relative to that plane’s origin point and are REQUIRED to be positive coordinates.

BPMN 2.0.2 page 375 (PDF 405):
> The waypoints of BPMNEdge are always relative to that plane’s origin point and are REQUIRED to be positive coordinates.

CMMN 1.1 page 85 (PDF 103):
>  Only positive coordinates are allowed for diagram elements that are nested in a CMMNDiagram.

DMN 1.2 page 97 (PDF 97):
> Only positive coordinates are allowed for diagram elements that are nested in a DMNDiagram.

### PR DESCRIPTION
**Pull request by nikku**
Builds upon https://github.com/camunda/camunda-modeler/pull/1169.

Closes #982

### CODE REVIEW

File: client/src/app/tabs/shared/fix-origin/FixOrigin.js [hunk 1]
```diff
@@ -0,0 +1,58 @@
+var PADDING = 100;
```
Comment (pinussilvestrus) [inline client/src/app/tabs/shared/fix-origin/FixOrigin.js]: any chance to use `const` and `let` inside this module?

Comment (nikku) [reply client/src/app/tabs/shared/fix-origin/FixOrigin.js]: I'll migrate the functionality to an external module (as a follow up step).

This will resolve the issue.
