### PR TITLE
fix: toggle linting only when error panel toggled

### LINKED ISSUE #3127: Error overlay does not open up the properties panel on single click
### Describe the bug

When we try to click on the error overlay and open up the properties panel it is not possible  with a single click rather we need to click twice to achieve the output.

### Steps to reproduce

1. Create a BPMN diagram with Camunda Platform 8
2.  Create any two tasks that would produce lint error
3. Now try to traverse between the lint error overlay of the tasks we could see sometimes on a single click the properties panel is open and the respective error is highlighted while sometimes it needs a double click on the overlay.

https://user-images.githubusercontent.com/85225325/189343200-5ff09fd4-ccdd-4de0-aa1b-8d23d2d5b4a7.mp4

### Expected behavior

On clicking the error overlay once the properties panel should be open

### Environment

- OS: [ Windows 10]
- Camunda Modeler Version: [5.3.0]
- Execution Platform: [ Camunda Cloud]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by philippfromme**
* activate and deactivate linting only on toggle error panel
* simplify implementation
* rename #onToggleLinting to #handleToggleLinting
* add linting annotations to Camunda 7 BPMN editor

---

Closes #3127

### CODE REVIEW

**Comment by philippfromme** [comment]
@barmac @pinussilvestrus 🏓

File: client/src/app/tabs/cloud-bpmn/BpmnEditor.js [hunk 1]
```diff
@@ -483,6 +487,8 @@ export class BpmnEditor extends CachedComponent {
         tab: 'linting'
       }
     });
+
+    this.getModeler().get('linting').activate();
```
Comment (nikku) [inline client/src/app/tabs/cloud-bpmn/BpmnEditor.js:491]: Duplication with first lines in method.

File: client/src/app/tabs/cloud-bpmn/BpmnEditor.js [hunk 2]
```diff
@@ -463,6 +463,8 @@ export class BpmnEditor extends CachedComponent {
         }
       });
 
+      this.getModeler().get('linting').activate();
```
Comment (nikku) [inline client/src/app/tabs/cloud-bpmn/BpmnEditor.js:466]: I don't understand this duplication.

Why don't we react to a `linting.activated` and trigger the `onLayoutChanged` from there? Overall there seems to be duplication going on here.

**Comment by philippfromme** [comment]
@nikku I've simplified the implementation to remove the redundant code. I also noticed that the linting annotations weren't included in the Camunda 7 BPMN modeler yet, so I added them. Once we allow users to add lint rules for both platforms that'll be useful.

**Review by nikku — APPROVED** [review]
Nice follow up improvements!
