### PR TITLE
fix(TaskTestingTab): add docs link

### LINKED ISSUE #5297: Add documentation link in task testing
### What should we do?

Add a link to documentation in task testing

### Why should we do it?

Missing documentation leaves the user in the wild.

### PR DESCRIPTION
**Pull request by philippfromme**
Links to https://docs.camunda.com/docs/components/modeler/desktop-modeler/task-testing/ ([still in progress](https://github.com/camunda/camunda-docs/pull/6736)).

electron_JQnOiLe529

Closes #5297

### Checklist

To ensure you provided everything we need to look at your PR:

* [x] __Brief textual description__ of the changes present
* [x] __Visual demo__ attached
* [ ] __Steps to try out__ present, i.e. [using the `@bpmn-io/sr` tool](https://github.com/bpmn-io/sr)
* [x] Related issue linked via `Closes {LINK_TO_ISSUE}` or `Related to {LINK_TO_ISSUE}`

### CODE REVIEW

File: client/src/app/panel/tabs/task-testing/TaskTestingTab.js [hunk 1]
```diff
@@ -179,6 +179,7 @@ export default function TaskTestingTab(props) {
           configureConnectionBannerTitle={ configureConnectionBannerTitle }
           configureConnectionBannerDescription={ configureConnectionBannerDescription }
           api={ taskTestingApi.getApi() }
+          documentationUrl={ 'https://docs.camunda.com/docs/components/modeler/desktop-modeler/task-testing/' }
```
Comment (nikku) [inline client/src/app/panel/tabs/task-testing/TaskTestingTab.js]:
```suggestion
          documentationUrl={ 'https://docs.camunda.com/docs/components/modeler/desktop-modeler/task-testing/?utm_source=modeler&utm_medium=referral' }
```

Add UTM tag, cf. https://github.com/camunda/camunda-modeler/issues/5281 and [existing uses](https://github.com/search?q=repo%3Acamunda%2Fcamunda-modeler%20utm&type=code)

**Review by barmac — APPROVED** [review]

File: client/src/app/panel/tabs/task-testing/TaskTestingTab.js (hunk 1 above)
Comment (philippfromme) [reply client/src/app/panel/tabs/task-testing/TaskTestingTab.js]: Oh, I didn't know about that. Thanks! 👍🏻
