### PR TITLE
Normalize Sentry events

### LINKED ISSUE #1831: Fix source maps not working in Camunda Modeler crash reports
__What should we do?__

* [x] Investigate why source maps in the client bundle are not working in our crash reports. (See [this comment](https://github.com/camunda/camunda-modeler/issues/1831#issuecomment-648676209).)
* [ ] Fix the situation

__Why should we do it?__

Source maps allow us to reliably reproduce issues recorded.

### PR DESCRIPTION
**Pull request by oguzeroglu**
__Which issue does this PR address?__

Closes #1831

**Best way to test this works**
Since we don't have this problem for dev builds, we need to create a buggy artifact to test this. Follow these steps:

1. Inject `SENTRY_DSN`, `SENTRY_AUTH_TOKEN`, `SENTRY_ORG` and `SENTRY_PROJECT` environment variables. They should be accessible from `client/webpack.config.js` These values can be found on our Sentry page. Ping @oguzeroglu if you don't know how to get those.
2. We don't want to pollute existing sourcemaps, so we need to change [this line](https://github.com/camunda/camunda-modeler/blob/c002e72af5c0147444af28edd1787e14def83fb8/client/webpack.config.js#L141) to `release: 'testRelease'`. For the same reason, change [this line](https://github.com/camunda/camunda-modeler/blob/c002e72af5c0147444af28edd1787e14def83fb8/client/src/plugins/error-tracking/ErrorTracking.js#L84) to `release: 'testRelease'` as well.
3. Inject a `throw new Error('TEST ERROR');` somewhere inside the client code. I usually inject this into the top of`DeploymentConfigModal#onClose` so that an exception is thrown every time I try to close the deployment modal.
4. `npm run build`
5. Reproduce the bug using the built artifact (by trying to close the deployment modal).
6. Go to Sentry, find the related error. Verify that Sentry shows correctly where the error occured and this warning does not exist:
Screenshot 2020-06-24 at 13 19 00

For questions ping @oguzeroglu.

**Why this error happens**
Unlike bpmn.io demo website, Camunda Modeler errors do not come from a static source. The error URL depends on where the users installed the app. That's why Sentry is unable to match uploaded sourcemaps to URL of exceptions.

Example:
Uploaded sourcemap: `public/2.2.js`
Error comes from: `/Users/Desktop/test/Camunda Modeler/app.asar/public/2.2.js`

That's why we need to normalize the URLs.

See [this comment](https://github.com/camunda/camunda-modeler/issues/1831#issuecomment-648676209).

Note that the official Electron Sentry SDK uses a similar technique to overcome this problem. Due to the fact that users may turn off the error tracking option on the run, we've chosen not to use the sentry-electron package, since it does not provide us such flexibility (we use sentry-browser and sentry-node libraries instead)

__Acceptance Criteria__

* [x] Corresponds to the concept 
* [x] Corresponds to the design 

__Definition of Done__

* [x] corresponds to [the design principles](https://github.com/bpmn-io/design-principles)
* [x] corresponds to [the code standards](https://github.com/bpmn-io/bpmn-js/blob/master/.github/CONTRIBUTING.md#creating-a-pull-request)
* [x] passes Continuous Integration checks
* [x] available as feature branch on GitHub
  * [x] contains the cleaned up commit history
  * [x] commit messages satisfy our [commit message guidelines](https://www.conventionalcommits.org/)
  * [x] a single commit closes the issue via Closes #issuenr

### CODE REVIEW

**Comment by pinussilvestrus** [comment]
Thanks for the detailed description! will have a look.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js [hunk 1]
```diff
@@ -357,8 +360,85 @@ describe('<ErrorTracking>', () => {
       { key: 'plugins', value: plugins.map(({ name }) => name) }
     );
   });
+
+
+  describe('Path normalization', () => {
+
+    it('should normalize Windows paths', () => {
+
+      return normalizationTest('/C:/Users/user/test-user/Desktop/Camunda/resources/app.asar/public/');
```
Comment (pinussilvestrus) [inline client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:369]: Just wondering, can this fail due to timeouts? Since `normalizationTest` is asynchronous, but the test is not.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js [hunk 2]
```diff
@@ -357,8 +360,85 @@ describe('<ErrorTracking>', () => {
...
+
+
+    it('should normalize dev paths', () => {
+
+      return normalizationTest('webpack-internal:///./src/plugins/camunda-plugin/deployment-tool/');
+    });
+  });
 });
 
+async function normalizationTest(prefix) {
```
Comment (pinussilvestrus) [inline client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:392]: maybe we can rename it to `expectNormalization`?

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:369]: AFAIK Mocha waits for the test to finish if you return a promise. Since normalizaionTest is async, it should return a Promise. So if this method throws an exception the test also fails.

File: client/src/plugins/error-tracking/ErrorTracking.js [hunk 3]
```diff
@@ -186,7 +195,39 @@ export default class ErrorTracking extends PureComponent {
...
+        frames.forEach((frame) => {
+          frame.filename = normalizeUrl(frame.filename);
+        });
+      });
+
+      return event;
+    } catch (err) {
+
+      // Don't loose the actual event in case things go wrong
+      return event;
```
Comment (pinussilvestrus) [inline client/src/plugins/error-tracking/ErrorTracking.js:219]: Is it intended to fail? Otherwise, this will hide errors from this implementation we might not see in the end.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 2 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:392]: Good idea

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: I don't see a reason why the normalization fails (it's just a regex replace operation). However if for some reason it fails, we still want to send the non-normalized original error event to Sentry. In that case we'd see a "Source code not found" error in Sentry and check why this operation failed using the actual data.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:369]: > AFAIK Mocha waits for the test to finish if you return a promise. 

Man, I always forget this aspect.

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: meta-question: When this piece of code would throw an error, because the normalization failed, would it then send this error to sentry?

Comment (oguzeroglu) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: Original event that we're trying to normalize: Yes
The error that we caused while normalizing the error: No

Rational of No:
Since this method is executed before we send events to Sentry, if we send additional stuff to Sentry at this point, we might easily cause some sort of infinite loop. IMO it's best if we don't send and additional error here. If we detect we're unable to normalize data through Sentry (the path we see would not be normalized then), we can investigate why this happened using the actual data itself. That's not very likely TBH. I was just being extra-cautious there.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (barmac) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js]: Windows paths look a bit different.

```suggestion
      return normalizationTest('C:\\Users\user\\test-user\\Desktop\\Camunda\\resources\\app.asar\\public');
```

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 2 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js]: Done via https://github.com/camunda/camunda-modeler/pull/1846/commits/dc92106c021ec390281d9d1216f23b3ee0790aa2

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js]: I copied this path from actual Sentry errors but maybe Sentry prints it like this. I'll add this as an additional case rather than converting the case.

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (barmac) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: Does it mean that if for some reason the block above fails, we send full path which may contain personal data?

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (barmac) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js]: Sure. It seems they are Unix-centric ;)

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: Yes, we send the event as is in that case. I'm not sure if this is considered personal data or not. It's just the application path.

Comment (barmac) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: I mean if it's like:

`/Users/maciej-barelkowski/workspace/bpmn-io/camunda-modeler`

then it's not anonymous anymore.

Comment (barmac) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: Cf. https://sentry.io/organizations/camunda-modeling/issues/1694263988/?project=5223041&query=is%3Aunresolved

Comment (pinussilvestrus) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: Why not simply raise an error if the before-event fails. Our test cases should be good enough to detect this before production.

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js (hunk 1 above)
Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js]: Done via https://github.com/camunda/camunda-modeler/pull/1846/commits/44d5a4c5a41f2c8a6c3ea68b62582c12361eee66

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (barmac) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: To be honest, I would just make sure that the try block never fails. Or maybe it already doesn't?

Comment (oguzeroglu) [reply client/src/plugins/error-tracking/ErrorTracking.js:219]: infinite

This is why I wanted to make sure we always catch errors here (not that it'll ever fail). In case the normalization fails, we might end up having some sort of infinite loop. Any opinions?

Comment (oguzeroglu) [reply client/src/plugins/error-tracking/ErrorTracking.js]: Here's the solution we discussed: https://github.com/camunda/camunda-modeler/pull/1846/commits/5460106b3f3e38c86adb45cb9a7bf79851c3eea9

**Comment by oguzeroglu** [comment]
Put [WIP] becuse I'll add normalization to backend errors as well.

File: client/src/plugins/error-tracking/ErrorTracking.js (hunk 3 above)
Comment (barmac) [reply client/src/plugins/error-tracking/ErrorTracking.js]: Good job!

**Comment by oguzeroglu** [comment]
Added path normalization to backend via https://github.com/camunda/camunda-modeler/pull/1846/commits/bcf4785a1164901037b2a6c3e8b855325421738c

Here's a dummy event we captured from backend: https://sentry.io/organizations/camunda-modeling/issues/1745565824/?project=5223041&query=is%3Aunresolved

File: client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js [hunk 4]
```diff
@@ -357,8 +360,89 @@ describe('<ErrorTracking>', () => {
...
     );
   });
+
+
+  describe('Path normalization', () => {
+
+    it('should normalize Windows paths', () => {
+
+      return expectNormalization('/C:/Users/user/test-user/Desktop/Camunda/resources/app.asar/public/');
+    });
```
Comment (pinussilvestrus) [inline client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:370]: Let's make sure we always have two lines between each unit test.

Comment (oguzeroglu) [reply client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js:370]: Done!
