### PR TITLE
fix(App): stop showing dialogs after first cancel

### LINKED ISSUE #4186: On quitting with unsaved files, "cancel" should prevent following prompts to save
### Describe the bug

Given multiple unsaved files are opened, when I try to exit and click "cancel", prompts are displayed for each file.

### Steps to reproduce

https://github.com/camunda/camunda-modeler/assets/28307541/7100b53c-ace3-4fff-a4bb-933210f516fd

### Expected behavior

The quitting action should be cancelled altogether and no more prompts should be displayed.

### Environment

- OS: [e.g. MacOS 10.2, Windows 10]
- Camunda Modeler Version: [e.g. 2.0.0]
- Execution Platform: [e.g. Camunda 7, Camunda 8]
- Installed plug-ins: [...]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marstamm**
closes #4186

Recording 2024-05-30 at 14 43 13

### CODE REVIEW

**Review by nikku — APPROVED** [review]
:clap:

File: client/src/app/App.js [hunk 1]
```diff
@@ -1992,13 +1992,14 @@ export class App extends PureComponent {
   async quit() {
     const { tabs } = this.state;
 
-    const quitTasks = tabs.map((tab) => {
-      return () => this.saveBeforeClose(tab);
-    });
-
-    const quitResults = await pSeries(quitTasks);
+    let canQuit = true;
+    for (const tab of tabs) {
```
Comment (barmac) [inline client/src/app/App.js:1996]: No magic, plain JS implementation 🚀
